'use client'
/** Object-centric Factory and Merchant workspace. All mutations use the authenticated API. */
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { t, fields, reasons, statuses, errors } from '../src/copy.ts'
import type { Fact, Id, Records } from '../src/schema.ts'
import type { WorkspaceView } from '../src/workspace-view.ts'
import { skills } from '../src/schema.ts'
import { commerceStyle } from '../src/workspace-style.ts'
import { StoreSettings } from './store-settings.tsx'
import type { StoreBinding } from '../src/store-wire.ts'

type Snapshot = WorkspaceView & { enterpriseLink: { returnUrl: string; sources: { sourceId: string; targetId: Id; kind: string; sourceRevision: number; confirmedAt: string | null; removed: boolean }[] } | null; runtimeConfigured: boolean; storeLink: { selected: StoreBinding | null; launches: (StoreBinding & { launchId: string })[] } | null }
type Input = { name: string; label: string; type?: string; optional?: boolean; value?: string }
type Send = (type: string, data: object) => Promise<unknown>
const uuid = () => crypto.randomUUID()
const inferred = (value: Fact['value']): Fact => ({ value, status: value === null ? 'UNKNOWN' : 'AI_INFERRED', visibility: 'CONFIDENTIAL', evidenceIds: [] })
const display = (value: unknown): string => value === null || value === undefined ? t('unknown') : Array.isArray(value) ? value.join(', ') : typeof value === 'boolean' ? t(value ? 'yes' : 'no') : String(value)
const factsFrom = (form: FormData, map: Record<string, string>, numbers: string[] = [], arrays: string[] = [], bools: string[] = []) => Object.fromEntries(Object.entries(map).map(([key, field]) => {
  const raw = String(form.get(key) ?? '').trim()
  return [field, inferred(bools.includes(key) ? form.get(key) === 'on' : !raw ? null : numbers.includes(key) ? Number(raw) : arrays.includes(key) ? raw.split(',').map(x => x.trim()) : raw)]
}))
function Form({ inputs, label, action, children }: { inputs: Input[]; label: string; action: (data: FormData) => Promise<unknown>; children?: ReactNode }) {
  const [busy, setBusy] = useState(false)
  return <form className="form" onSubmit={async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = e.currentTarget; setBusy(true); try { await action(new FormData(form)) } finally { setBusy(false) } }}>
    <div className="form-grid">{inputs.map(i => <label key={i.name}>{i.label}<input name={i.name} type={i.type ?? 'text'} required={!i.optional && i.type !== 'checkbox'} defaultValue={i.value} step={i.type === 'number' ? 'any' : undefined}/></label>)}</div>{children}<button disabled={busy}>{busy ? t('loading') : label}</button>
  </form>
}
function Facts({ facts, kind, record, send }: { facts: Record<string, Fact>; kind: string; record: { id: Id; revision: number }; send: Send }) {
  const [selected, setSelected] = useState<string[]>([]), [disclose, setDisclose] = useState(false)
  return <div><p className="muted">{t('reviewFacts')}</p><div className="facts">{Object.entries(facts).map(([key, f]) => <label className="fact" key={key}><input type="checkbox" checked={selected.includes(key)} disabled={f.value === null || f.status === 'CONFLICTING'} onChange={e => setSelected(e.target.checked ? [...selected, key] : selected.filter(k => k !== key))}/><span><strong>{fields[key] ?? key}</strong><span>{display(f.value)}</span></span><small>{statuses[f.status]} · {f.evidenceIds.length} {t('evidence')}</small></label>)}</div><label className="check"><input type="checkbox" checked={disclose} onChange={e => setDisclose(e.target.checked)}/>{t('public')}</label><button disabled={!selected.length} onClick={async () => { await send('facts.confirm', { entityType: kind, id: record.id, expectedRevision: record.revision, fields: selected, visibility: disclose ? 'PUBLIC' : 'CONFIDENTIAL' }); setSelected([]) }}>{t('confirm')}</button></div>
}
function Samples({ samples, factory, send }: { samples: Records['sample'][]; factory: boolean; send: Send }) {
  return <div className="cards">{samples.map(s => <section className="card" key={s.id}><span className="badge">{statuses[s.status]}</span><h3>{s.variant}</h3><p>{s.shippingAddress}</p><p>{s.supplierResponse}</p><p>{s.tracking}</p><p>{t('sampleCost')}: {display(s.sampleCost)} {s.currency} · {t('shippingCost')}: {display(s.shippingCost)}</p>
    {factory && ['REQUESTED', 'CONFIRMED'].includes(s.status) && <Form inputs={[{ name: 'sampleCost', label: t('sampleCost'), type: 'number', value: String(s.sampleCost ?? '') }, { name: 'shippingCost', label: t('shippingCost'), type: 'number', value: String(s.shippingCost ?? '') }, { name: 'supplierResponse', label: t('response'), value: s.supplierResponse }, { name: 'tracking', label: t('tracking'), optional: s.status === 'REQUESTED', value: s.tracking }]} label={t(s.status === 'REQUESTED' ? 'confirmSample' : 'ship')} action={f => send('sample.transition', { id: s.id, expectedRevision: s.revision, status: s.status === 'REQUESTED' ? 'CONFIRMED' : 'SHIPPED', sampleCost: Number(f.get('sampleCost')), shippingCost: Number(f.get('shippingCost')), supplierResponse: f.get('supplierResponse'), tracking: f.get('tracking') })}/>}
    {!factory && <div className="actions">{(s.status === 'SHIPPED' ? [['DELIVERED', 'delivered']] : s.status === 'DELIVERED' ? [['ACCEPTED', 'accept'], ['REJECTED', 'reject']] : ['REQUESTED', 'CONFIRMED'].includes(s.status) ? [['CANCELLED', 'cancel']] : []).map(([status, label]) => <button key={status} onClick={() => send('sample.transition', { id: s.id, expectedRevision: s.revision, status, sampleCost: s.sampleCost, shippingCost: s.shippingCost, supplierResponse: s.supplierResponse, tracking: s.tracking })}>{t(label as 'accept')}</button>)}</div>}
    {!factory && s.status === 'ACCEPTED' && <details><summary>{t('startTest')}</summary><Form inputs={[{ name: 'price', label: `${t('targetPrice')} · ${s.currency}`, type: 'number' }, { name: 'margin', label: t('marginTarget'), type: 'number', optional: true }, { name: 'inventory', label: t('inventory') }]} label={t('prepare')} action={f => send('launch.prepare', { sampleId: s.id, targetPrice: Number(f.get('price')), targetMargin: f.get('margin') ? Number(f.get('margin')) : null, initialInventoryModel: f.get('inventory') })}/></details>}
  </section>)}</div>
}

/** Render the same business controls in Next.js or the authenticated enterprise panel.
 * @param props - Optional enterprise API prefix and panel-return action; absent for standalone login.
 * @returns Login or role-specific business pages.
 */
export function CommerceWorkspace({ apiBase = '/api', onReturn }: { apiBase?: string; onReturn?: () => void }) {
  const embedded = Boolean(onReturn)
  const [token, setToken] = useState(''), [data, setData] = useState<Snapshot | null>(null), [runtimeStatus, setRuntimeStatus] = useState(false), [page, setPage] = useState('home'), [error, setError] = useState(''), [busy, setBusy] = useState(false), [agentResult, setAgentResult] = useState<{ explanation: string; commands: unknown[] } | null>(null)
  const handoff = useRef<Promise<{ token: string; snapshot: Snapshot }> | null>(null)
  useEffect(() => {
    if (!embedded) return
    const controller = new AbortController()
    setBusy(true)
    void fetch(`${apiBase}/workspace`, { signal: controller.signal }).then(async r => {
      const result = await r.json()
      if (!r.ok) throw new Error(errors[result.error] ?? errors.operation_failed)
      if (!controller.signal.aborted) setData(result as Snapshot)
    }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : errors.operation_failed!) }).finally(() => { if (!controller.signal.aborted) setBusy(false) })
    return () => controller.abort()
  }, [apiBase, embedded])
  useEffect(() => {
    if (embedded) return
    let active = true
    if (!handoff.current) {
      const code = new URLSearchParams(window.location.hash.slice(1)).get('handoff')
      if (!code) return
      window.history.replaceState(null, '', window.location.pathname + window.location.search)
      handoff.current = (async () => {
        const response = await fetch('/api/integration/exchange', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ code }) })
        if (!response.ok) throw new Error(t('handoffExpired'))
        const session = await response.json() as { token: string }
        const workspace = await fetch('/api/workspace', { headers: { authorization: `Bearer ${session.token}` } })
        if (!workspace.ok) throw new Error(t('handoffExpired'))
        return { token: session.token, snapshot: await workspace.json() as Snapshot }
      })()
    }
    setBusy(true)
    void handoff.current.then(value => { if (active) { setToken(value.token); setData(value.snapshot) } }).catch(e => { if (active) setError(e instanceof Error ? e.message : t('handoffExpired')) }).finally(() => { if (active) setBusy(false) })
    return () => { active = false }
  }, [embedded])
  async function request(path: string, body?: unknown): Promise<unknown> {
    const r = await fetch(`${apiBase}/${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { ...(!embedded ? { Authorization: `Bearer ${token}` } : {}), ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) })
    const result = await r.json() as { error?: string; fields?: string[] }
    if (!r.ok) throw new Error(errors[result.error ?? 'operation_failed'] ?? errors.operation_failed)
    return result
  }
  async function load() { setData(await request('workspace') as Snapshot) }
  async function run(path: string, body?: unknown) { setBusy(true); setError(''); try { const result = await request(path, body); await load(); return result } catch (e) { setError(e instanceof Error ? e.message : 'operation_failed'); return null } finally { setBusy(false) } }
  const send: Send = (type, values) => run('commands', { requestId: uuid(), type, ...values })
  const factory = data?.role === 'factory'
  const nav = factory ? ['home', 'company', 'products', 'opportunities', 'samples'] : ['home', 'forYou', 'samples', 'launches']
  const actor = data?.subjectId
  const productForm = (key?: Id, revision = 0) => <Form inputs={[{ name: 'name', label: t('productName') }, { name: 'category', label: t('category') }, { name: 'manufacturer', label: t('manufacturer') }, { name: 'specs', label: t('specs') }, { name: 'image', label: t('image'), type: 'url' }, { name: 'moq', label: t('moq'), type: 'number', optional: true }, { name: 'sample', label: t('samplePolicy'), optional: true }, { name: 'lead', label: t('leadTime'), optional: true }, { name: 'quote', label: t('quote'), optional: true }, { name: 'currency', label: t('currency'), optional: true }, { name: 'label', label: t('privateLabel'), type: 'checkbox' }, { name: 'shipping', label: t('fulfillment'), optional: true }, { name: 'cost', label: t('cost'), type: 'number', optional: true }]} label={t('save')} action={f => send('product.save', { id: key ?? uuid(), expectedRevision: revision, facts: factsFrom(f, { name: 'identity.product_name', category: 'identity.category', manufacturer: 'identity.manufacturer', specs: 'specifications.technical_specs', image: 'evidence.product_images', moq: 'commercial.moq', sample: 'commercial.sample', lead: 'commercial.lead_time', quote: 'commercial.price_basis', currency: 'commercial.currency', label: 'customization.private_label', shipping: 'fulfillment.shipping', cost: 'commercial.cost' }, ['moq', 'cost'], ['image'], ['label']) })}><p className="muted">{t('imageHint')}</p></Form>
  if (!data && embedded) return <div className="commerce-surface commerce-embedded"><style>{commerceStyle}</style><section className="card" role="status"><p>{busy ? t('loading') : error}</p><div className="actions"><button disabled={busy} onClick={() => run('workspace')}>{t('refresh')}</button><button className="secondary" onClick={onReturn}>{t('backToEnterprise')}</button></div></section></div>
  if (!data) return <div className="commerce-surface"><style>{commerceStyle}</style><main className="login"><div className="mark">CW</div><p className="eyebrow">{t('noPublic')}</p><h1>{t('brand')}</h1><p>{t('tagline')}</p><form onSubmit={async e => { e.preventDefault(); await run('workspace') }}><label>{t('credential')}<input type="password" autoComplete="off" required value={token} onChange={e => setToken(e.target.value)}/></label><p className="muted">{t('credentialHint')}</p><button disabled={busy}>{t('connect')}</button></form>{error && <p role="alert">{t('error')}: {error}</p>}</main></div>
  return <div className={`commerce-surface${embedded ? ' commerce-embedded' : ''}`}><style>{commerceStyle}</style><div className="shell"><aside><a className="brand" href="#" onClick={e => { e.preventDefault(); setPage('home') }}><span className="mark">CW</span>{t('brand')}</a><p className="eyebrow">{t(factory ? 'factory' : 'merchant')}</p><nav>{[...nav, 'ask', 'settings'].map(key => <button className={page === key ? 'active' : ''} key={key} onClick={() => setPage(key)}>{t(key as 'home')}</button>)}</nav>{embedded ? <button className="secondary" onClick={onReturn}>{t('backToEnterprise')}</button> : data.enterpriseLink && <a href={data.enterpriseLink.returnUrl}>{t('backToEnterprise')}</a>}<p className="sidebar-note">{t('tagline')}</p>{!embedded && <button className="subtle" onClick={async () => { try { await request('integration/logout', {}) } finally { setToken(''); setData(null); setAgentResult(null) } }}>{t('logout')}</button>}</aside><main className="workspace"><header><div><p className="eyebrow">{t('noPublic')}</p><h1>{t(page as 'home')}</h1></div><button className="secondary" disabled={busy} onClick={() => run('workspace')}>{busy ? t('loading') : t('refresh')}</button></header>{error && <div className="alert" role="alert">{t('error')}: {error}</div>}
    {data.enterpriseLink && page === 'home' && <section className="card"><h2>{t('connectedEnterprise')}</h2><p>{t(factory ? 'linkedHint' : 'linkedMerchantHint')}</p>{factory && !data.enterpriseLink.sources.length && <p>{t('linkedEmpty')}</p>}{embedded ? <button className="secondary" onClick={onReturn}>{t('refreshFromEnterprise')}</button> : <a href={data.enterpriseLink.returnUrl}>{t('refreshFromEnterprise')}</a>}<details><summary>{t('sourceVersions')}</summary>{data.enterpriseLink.sources.map(source => <p key={source.sourceId}>{source.sourceId} · {t('revision')} {source.sourceRevision} · {source.removed ? t('sourceRemoved') : source.confirmedAt ? `${t('sourceReviewed')} ${source.confirmedAt}` : t('missing')}</p>)}</details></section>}
    {page === 'home' && <><div className="hero"><p className="eyebrow">{t(factory ? 'factory' : 'merchant')}</p><h2>{t('tagline')}</h2><button onClick={() => setPage('ask')}>{t('ask')} ↗</button></div><div className="stats">{(data.role === 'factory' ? [[t('discovered'), data.products.length], [t('ready'), data.products.filter(p => p.readiness.status === 'OPPORTUNITY_READY').length], [t('available'), data.opportunities.filter(o => o.status === 'AVAILABLE').length], [t('activeSamples'), data.samples.length]] : [[t('forYou'), data.matches.length], [t('activeSamples'), data.samples.filter(s => !['ACCEPTED', 'REJECTED', 'CANCELLED'].includes(s.status)).length], [t('live'), data.launches.filter(l => l.status === 'LIVE' || l.status === 'SCALE').length], [t('orders'), data.performance.reduce((sum, p) => sum + p.orders, 0)]]).map(([label, value]) => <section className="stat" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><section className="card"><h2>{t('actionNeeded')}</h2>{data.role === 'factory' ? data.products.map(p => <div className="row" key={p.id}><strong>{display(p.passport.facts['identity.product_name']?.value)}</strong><p>{p.readiness.missing.map(k => fields[k] ?? k).join(' · ') || t('ready')}</p><button className="secondary" onClick={() => setPage('products')}>{t('products')}</button></div>) : <p>{t('matchHint')}</p>}</section></>}
    {page === 'company' && data.role === 'factory' && <section className="card"><h2>{t('company')}</h2>{data.company && <Facts facts={data.company.facts} record={data.company} kind="company" send={send}/>}<details open={!data.company}><summary>{t('createCompany')}</summary><Form inputs={[{ name: 'name', label: t('companyName') }, { name: 'contact', label: t('contact') }, { name: 'factory', label: t('factoryConfirmation'), type: 'checkbox' }]} label={t('save')} action={f => send('company.save', { id: actor, expectedRevision: data.company?.revision ?? 0, facts: factsFrom(f, { name: 'legal_name', contact: 'contacts', factory: 'factory_status' }, [], [], ['factory']) })}/></details></section>}
    {page === 'products' && data.role === 'factory' && <><section className="card"><details><summary>{t('newProduct')}</summary>{productForm()}</details></section>{data.products.map(p => <section className="card" key={p.id}><span className="badge">{statuses[p.readiness.status]}</span><h2>{display(p.passport.facts['identity.product_name']?.value)}</h2><Facts facts={p.passport.facts} kind="passport" record={p.passport} send={send}/><details><summary>{t('save')}</summary>{productForm(p.id, p.passport.revision)}</details>{p.readiness.status === 'OPPORTUNITY_READY' && <details><summary>{t('build')}</summary><Form inputs={[{ name: 'market', label: t('market') }, { name: 'brand', label: t('preferred') }, { name: 'audience', label: t('audience') }, { name: 'price', label: t('retail'), type: 'number', optional: true }]} label={t('build')} action={f => send('opportunity.build', { productId: p.id, targetMarket: f.get('market'), targetBrandTypes: [f.get('brand')], targetCustomerTypes: [f.get('audience')], suggestedRetailPrice: f.get('price') ? Number(f.get('price')) : null, currency: p.passport.facts['commercial.currency']?.value, launchRequirements: [] })}/></details>}</section>)}</>}
    {page === 'opportunities' && data.role === 'factory' && <div className="cards">{data.opportunities.map(o => <section className="card" key={o.id}><span className="badge">{statuses[o.status]}</span><h2>{display(data.products.find(p => p.id === o.productId)?.passport.facts['identity.product_name']?.value)}</h2><p>{o.targetMarket} · {o.targetCustomerTypes.join(', ')}</p><p>{t('retail')}: {display(o.suggestedRetailPrice)} {o.currency}</p><button onClick={() => send('opportunity.release', { id: o.id, expectedRevision: o.revision, available: o.status !== 'AVAILABLE' })}>{t(o.status === 'AVAILABLE' ? 'pause' : 'release')}</button></section>)}</div>}
    {page === 'forYou' && data.role === 'merchant' && <><p>{t('matchHint')}</p><button onClick={() => send('match.run', {})}>{t('match')}</button><div className="cards">{data.matches.map(m => <section className="card opportunity" key={m.id}>{Array.isArray(m.facts['evidence.product_images']?.value) && <img src={m.facts['evidence.product_images'].value[0]} alt={display(m.facts['identity.product_name']?.value)}/>}<span className="badge">{t('fits')}</span><h2>{display(m.facts['identity.product_name']?.value)}</h2><p>{m.explanation.audience}</p><dl>{[['retail', m.opportunity.suggestedRetailPrice], ['cost', m.facts['commercial.cost']?.value], ['moq', m.facts['commercial.moq']?.value], ['samplePolicy', m.facts['commercial.sample']?.value], ['leadTime', m.facts['commercial.lead_time']?.value], ['privateLabel', m.facts['customization.private_label']?.value], ['fulfillment', m.facts['fulfillment.shipping']?.value]].map(([key, v]) => <div key={String(key)}><dt>{t(key as 'retail')}</dt><dd>{display(v)}</dd></div>)}</dl><p>{m.explanation.margin}</p><details><summary>{t('why')}</summary>{Object.entries(m.explanation).map(([key, text]) => <p key={key}>{text}</p>)}<h3>{t('risks')}</h3>{m.risks.map(r => <p key={r}>{r}</p>)}<h3>{t('unknowns')}</h3>{m.unknowns.map(r => <p key={r}>{r}</p>)}</details><div className="actions"><button className="secondary" onClick={() => send('match.feedback', { id: m.id, expectedRevision: m.revision, feedback: 'SAVED', reason: null })}>{t('saved')}</button><button className="secondary" onClick={() => { setPage('ask') }}>{t('ask')}</button></div><details><summary>{t('notInterested')}</summary><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void send('match.feedback', { id: m.id, expectedRevision: m.revision, feedback: 'NOT_INTERESTED', reason: f.get('reason') }) }}><label>{t('reason')}<select name="reason">{Object.entries(reasons).map(([v, label]) => <option value={v} key={v}>{label}</option>)}</select></label><button>{t('notInterested')}</button></form></details><details><summary>{t('requestSample')}</summary><Form inputs={[{ name: 'variant', label: t('variant') }, { name: 'address', label: t('address') }]} label={t('requestSample')} action={f => send('sample.request', { matchId: m.id, variant: f.get('variant'), shippingAddress: f.get('address') })}/></details></section>)}</div></>}
    {page === 'samples' && <Samples samples={data.samples} factory={factory} send={send}/>}
    {page === 'launches' && data.role === 'merchant' && data.launches.map(l => <section className="card" key={l.id}><span className="badge">{statuses[l.status]}</span><h2>{data.listings.find(x => x.launchId === l.id)?.title}</h2><p>{t('targetPrice')}: {l.targetPrice} {l.currency}</p><p className="muted">{t('draftHint')}</p>{data.storeLink?.launches.filter(s => s.launchId === l.id).map(s => <p key={s.launchId}>{t('launchStore')}: {s.domain} · {s.publicationName}</p>)}<details><summary>{t('listing')}</summary><pre>{data.listings.find(x => x.launchId === l.id)?.description}</pre></details><details><summary>{t('artifacts')}</summary><p>{t('briefs')}</p>{data.artifacts.filter(a => a.launchId === l.id).map(a => <p key={a.id}>{a.content}</p>)}</details><div className="actions">{l.status === 'PREPARING' && <button onClick={() => run('shopify/draft', { id: l.id, expectedRevision: l.revision })}>{t('draft')}</button>}{l.status === 'READY' && <button onClick={() => send('approval.request', { launchId: l.id, expectedRevision: l.revision })}>{t('review')}</button>}{data.approvals.filter(a => a.launchId === l.id).map(a => <div key={a.id}><span>{statuses[a.status]} </span>{a.status === 'PENDING' && <button onClick={() => send('approval.decide', { id: a.id, expectedRevision: a.revision, approve: true })}>{t('approve')}</button>}{a.status === 'APPROVED' && <button onClick={() => run('shopify/publish', { id: a.id })}>{t('publish')}</button>}{['UNCERTAIN', 'EXECUTING'].includes(a.status) && <button onClick={() => run('shopify/reconcile', { id: a.id })}>{t('reconcile')}</button>}</div>)}</div>
      {['LIVE', 'SCALE', 'PAUSED', 'STOPPED'].includes(l.status) && <details><summary>{t('recordPerformance')}</summary><Form inputs={[{ name: 'sourceReference', label: t('sourceReference') }, { name: 'periodStart', label: t('periodStart'), type: 'datetime-local' }, { name: 'periodEnd', label: t('periodEnd'), type: 'datetime-local' }, ...(['views', 'addToCart', 'orders', 'unitsSold', 'revenue', 'refunds'] as const).map(name => ({ name, label: t(({ views: 'views', addToCart: 'carts', orders: 'orders', unitsSold: 'units', revenue: 'revenue', refunds: 'refunds' } as const)[name]), type: 'number', optional: name === 'views' || name === 'addToCart' }))]} label={t('record')} action={f => send('performance.record', { launchId: l.id, sourceReference: f.get('sourceReference'), periodStart: new Date(String(f.get('periodStart'))).toISOString(), periodEnd: new Date(String(f.get('periodEnd'))).toISOString(), currency: l.currency, ...Object.fromEntries(['views', 'addToCart', 'orders', 'unitsSold', 'revenue', 'refunds'].map(k => [k, f.get(k) ? Number(f.get(k)) : null])) })}/></details>}
      {data.performance.filter(p => p.launchId === l.id).map(p => <div className="row" key={p.id}><h3>{t('performance')}</h3><p>{p.orders} {t('orders')} · {p.revenue} {p.currency} {t('revenue')}</p><p>{p.sourceReference}</p><div className="actions">{(['STOP', 'ITERATE', 'SCALE'] as const).map(d => <button className="secondary" key={d} onClick={() => send('launch.decision', { id: l.id, expectedRevision: l.revision, decision: d, performanceId: p.id })}>{t(d.toLowerCase() as 'stop')}</button>)}</div><p className="muted">{t('decisionHint')}</p></div>)}</section>)}
    {page === 'settings' && <>{data.storeLink && <StoreSettings selected={data.storeLink.selected} run={run}/>}<section className="card"><h2>{t('runtimeConnection')}</h2><p>{t('runtimeHint')}</p><button disabled={busy || !data.runtimeConfigured} onClick={async () => { setRuntimeStatus(false); const result = await run('agent/check', {}); if (result) setRuntimeStatus(true) }}>{t('checkRuntime')}</button>{runtimeStatus && <p>{t('runtimeConnected')}</p>}</section><section className="card"><p>{t('settingsHint')}</p><p>{t('importHint')}</p><p>{t('readOnly')}</p>{!factory && <button onClick={async () => { const catalog = await run('shopify/catalog', {}); if (catalog) setAgentResult({ explanation: JSON.stringify(catalog, null, 2), commands: [] }) }}>{t('shopifyCatalog')}</button>}</section>{data.role === 'merchant' && <section className="card"><h2>{t('profile')}</h2>{data.profile && <Facts kind="merchantProfile" record={data.profile} facts={data.profile.facts} send={send}/>}<details open={!data.profile}><summary>{t('createProfile')}</summary><Form inputs={[{ name: 'name', label: t('merchantName') }, { name: 'market', label: t('market') }, { name: 'audience', label: t('brandAudience') }, { name: 'preferred', label: t('preferred') }, { name: 'categories', label: t('currentCategories') }, { name: 'min', label: t('priceMin'), type: 'number' }, { name: 'max', label: t('priceMax'), type: 'number' }, { name: 'moq', label: t('maxMoq'), type: 'number' }, { name: 'currency', label: t('currency') }, { name: 'margin', label: t('marginTarget'), type: 'number', optional: true }, { name: 'label', label: t('privateLabel'), type: 'checkbox' }]} label={t('save')} action={f => send('merchant.save', { id: actor, expectedRevision: data.profile?.revision ?? 0, name: f.get('name'), facts: factsFrom(f, { name: 'name', market: 'market', audience: 'brand.audience', preferred: 'strategy.preferred_categories', categories: 'catalog.current_categories', min: 'brand.price_min', max: 'brand.price_max', moq: 'strategy.max_moq', currency: 'strategy.currency', margin: 'strategy.target_margin', label: 'strategy.private_label' }, ['min', 'max', 'moq', 'margin'], ['preferred', 'categories'], ['label']) })}/></details></section>}</>}
    {page === 'ask' && <section className="card"><p>{t('sourceHint')}</p><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await run('agent', { skill: f.get('skill'), goal: f.get('goal'), sources: f.get('text') ? [{ reference: f.get('reference'), text: f.get('text') }] : [] }); if (r) setAgentResult(r as typeof agentResult) }}><label>{t('skill')}<select name="skill">{skills.map(s => <option key={s}>{s}</option>)}</select></label><label>{t('goal')}<textarea name="goal" required/></label><label>{t('source')}<input name="reference"/></label><label>{t('sourceText')}<textarea name="text" rows={8}/></label><button disabled={busy}>{t('generate')}</button></form></section>}
    {agentResult && ['ask', 'settings'].includes(page) && <section className="card"><pre>{agentResult.explanation}</pre>{agentResult.commands.map((c, i) => <details key={i}><summary>{t('apply')} {i + 1}</summary><pre>{JSON.stringify(c, null, 2)}</pre><button onClick={() => run('agent/apply', c)}>{t('apply')}</button></details>)}</section>}
  </main></div></div>
}
