/** Versioned transfer of enterprise facts; source review is separate from commerce confirmation. */
import { z } from 'zod'
import { companyFields, productFields, fact } from './schema.ts'

const field = z.object({ value: fact.shape.value, sourceStatus: z.string().min(1).max(80), citation: z.string().max(3000), validUntil: z.iso.datetime().nullable(), conflicting: z.boolean() }).strict()
const record = { sourceId: z.string().min(1).max(200), revision: z.number().int().nonnegative(), confirmedAt: z.iso.datetime().nullable() }
/** Complete current catalog, including explicit absence for revoking imported sources. */
export const enterpriseTransfer = z.object({
  version: z.literal(1),
  company: z.object({ ...record, facts: z.partialRecord(z.enum(companyFields), field) }).strict().nullable(),
  products: z.array(z.object({ ...record, facts: z.partialRecord(z.enum(productFields), field) }).strict()).max(1000),
}).strict().refine(v => !v.products.length || v.company !== null, 'Products require a company')
  .refine(v => new Set(v.products.map(p => p.sourceId)).size === v.products.length, 'Product source ids must be unique')
/** Parsed transfer generated by the enterprise deployment. */
export type EnterpriseTransfer = z.infer<typeof enterpriseTransfer>
