/** Preview-only copy. All business values describe synthetic component examples. */
export const designZh = {
  brand: '序 · FORM', brandCaption: '企业工作台组件', navLabel: '组件目录', navOverview: '设计概览', navWorkflow: '资料与审阅', navProducts: '产品与动态', navFoundation: '基础组件',
  navFoot: '少一些噪音，多一些秩序。', edition: 'DESIGN COLLECTION / 01', version: '组件集 v1.0', preview: '交互预览 · 示例数据', theme: '切换深浅主题', language: 'Switch to English',
  title: '让复杂工作，变得从容。', introduction: '从一份资料到一款产品，让每一步都有清晰、美好的承载。', jump: '探索组件',
  heroLabel: 'WORKSPACE / 工作空间', heroTitle: '好的秩序，\n是下一步的起点。', heroText: '将信息整理、内容审阅与产品展示，编排成自然流畅的工作体验。', heroAction: '体验资料审阅', heroMeta: '13 个组件 · 2 套主题 · 响应式布局',
  paletteTitle: '自然、克制、有层次', paletteSubtitle: 'COLOR & MATERIAL', paletteNames: ['松绿', '青柠', '暖白', '墨色'], paletteNote: '用留白建立层次，用色彩指引行动。',
  metrics: [{ label: '资料总量', value: '24', detail: '文档、图片与表格', icon: 'commercial_policy' }, { label: '待核对内容', value: '03', detail: '让不确定的信息清晰可见', icon: 'evidence' }, { label: '产品档案', value: '08', detail: '从素材到完整的产品表达', icon: 'offering' }],
  workflowTitle: '每一步，都有迹可循', workflowDescription: '资料列表、处理进度与人工审阅，保持同一种表达。', flowLabel: '建档进度',
  steps: [{ label: '导入资料', detail: '原始文件已保留' }, { label: '整理内容', detail: '信息已提取' }, { label: '人工核对', detail: '等待你的确认' }, { label: '形成档案', detail: '核对后继续' }],
  sourcesTitle: '资料清单', sourcesCaption: 'SOURCE LIBRARY', sourceCount: '3 份示例资料', filterLabel: '筛选资料状态', all: '全部', pending: '待核对', completed: '已整理', searchLabel: '查找资料', searchPlaceholder: '搜索名称或格式…',
  files: [{ id: 'catalog', name: '产品目录 · 春夏系列.pdf', detail: '12 页 · 3.8 MB · 产品资料', format: 'PDF', status: '待核对' }, { id: 'company', name: '公司介绍与制造能力.docx', detail: '6 页 · 860 KB · 企业资料', format: 'DOCX', status: '已整理' }, { id: 'pricing', name: '产品规格与报价表.xlsx', detail: '3 个工作表 · 128 KB · 商业资料', format: 'XLSX', status: '已整理' }],
  view: '查看', noResults: '没有找到匹配资料', noResultsHint: '试试其他关键词，或切换资料状态。', reset: '重置筛选',
  reviewEyebrow: 'HUMAN REVIEW / 人工核对', reviewTitle: '把最后的判断，留给你。', reviewText: '这款轻量棉麻面料适用于日常服装系列。成分、克重与供货规格已从资料中整理，等待与原件逐项核对。', citation: '产品目录.pdf · 第 4 页 · 示例引用', reviewNote: '确认表达的是“已核对”，不代表独立认证或公开发布。', approve: '确认内容', needsInput: '需要补充', approved: '已核对', needsInputStatus: '待补充', undo: '重新核对',
  reviewApprovedToast: '示例内容已核对。此操作未修改企业数据。', reviewInputToast: '示例已标记为待补充。',
  productTitle: '让信息，有自己的质感', productDescription: '产品卡片、信息项与动态记录，可独立使用，也能自由组合。',
  productCategory: 'MATERIAL COLLECTION / 材料系列', productName: '轻量棉麻 · CL—021', productText: '自然肌理，柔和触感。让关键规格、资料来源与产品状态共同构成一张完整卡片。', productStatus: '草稿', productMaterial: '成分', productMaterialValue: '棉麻混纺', productWeight: '克重', productWeightValue: '180 g/m²', productCode: '系列', productCodeValue: 'ESSENTIAL',
  materialArt: '示意材料色卡，不是真实产品图片', materialArtLabel: 'MATERIAL STUDY — 021', materialArtFoot: 'SAGE / SAND / STONE', productOpen: '查看产品', save: '收藏示例', saved: '已收藏',
  activityTitle: '最近动态', activityCaption: 'ACTIVITY', activityLabel: '示例操作记录', activities: [{ title: '目录资料已整理', detail: '提取 8 款产品的基础信息', time: '14:32' }, { title: '等待内容核对', detail: '3 处规格需要与原件确认', time: '14:28' }, { title: '导入企业资料', detail: '原文件与目录结构已保留', time: '14:20' }],
  emptyTitle: '给下一个想法，留个位置', emptyText: '一份清楚的资料，是一款好产品的开始。', emptyAction: '创建示例草稿', createdTitle: '你的示例草稿', createdText: '草稿状态已展示。刷新预览即可还原。',
  foundationsTitle: '细节统一，组合自由', foundationsDescription: '稳定的尺寸、清晰的状态和适度的反馈，让交互自然发生。', buttonsTitle: '行动按钮', buttonsCaption: 'ACTIONS', primary: '主要操作', secondary: '次要操作', quiet: '轻量操作', loading: '正在处理', disabled: '暂不可用', actionToast: '这是组件交互示例，没有发起业务操作。',
  statusesTitle: '状态语言', statusesCaption: 'STATUS', neutral: '草稿', success: '已完成', warning: '待确认', info: '处理中', danger: '需重试',
  fieldsTitle: '让输入更有把握', fieldsCaption: 'FORM FIELDS', fieldName: '产品名称', fieldPlaceholder: '例如：轻量棉麻面料', fieldHint: '使用清楚、便于检索的名称。', fieldEmail: '联系邮箱', fieldEmailPlaceholder: 'name@company.com', emailError: '请输入完整的邮箱地址，例如 name@company.com。',
  footer: 'FORM — 为真实工作，设计安静而清晰的界面。', footerNote: '全部数据均为设计示例，不连接企业资料。', close: '关闭', dialogTitle: '示例详情', dialogNote: '这是组件预览。实际使用时，由业务页面提供真实内容与操作。', dialogSourceText: '资料已按原目录保存。这里可呈现完整预览、出处、页码与处理记录。',
} as const

type Copy = { [K in keyof typeof designZh]: typeof designZh[K] extends string ? string : typeof designZh[K] extends readonly string[] ? readonly string[] : typeof designZh[K] extends readonly (infer Item)[] ? { readonly [P in keyof Item]: string }[] : never }

/** English preview uses the same fields as the Chinese dictionary. */
export const designEn: Copy = {
  brand: '序 · FORM', brandCaption: 'Enterprise components', navLabel: 'Component directory', navOverview: 'Overview', navWorkflow: 'Sources & review', navProducts: 'Products & activity', navFoundation: 'Foundations', navFoot: 'Less noise. More clarity.', edition: 'DESIGN COLLECTION / 01', version: 'Collection v1.0', preview: 'Interactive preview · Sample data', theme: 'Switch light or dark theme', language: '切换为中文',
  title: 'Make room for focused work.', introduction: 'From the first source to a finished product, give every step a considered place.', jump: 'Explore components', heroLabel: 'WORKSPACE', heroTitle: 'A little order.\nA clearer next step.', heroText: 'Connect source materials, thoughtful review and product stories in one calm working experience.', heroAction: 'Try a content review', heroMeta: '13 components · 2 themes · Responsive',
  paletteTitle: 'Grounded. Quiet. Considered.', paletteSubtitle: 'COLOR & MATERIAL', paletteNames: ['Pine', 'Lime', 'Ivory', 'Ink'], paletteNote: 'Space creates hierarchy. Color guides action.', metrics: [{ label: 'Source materials', value: '24', detail: 'Documents, images and spreadsheets', icon: 'commercial_policy' }, { label: 'Awaiting review', value: '03', detail: 'Keep uncertain information visible', icon: 'evidence' }, { label: 'Product records', value: '08', detail: 'From materials to a complete story', icon: 'offering' }],
  workflowTitle: 'A traceable path forward', workflowDescription: 'Source lists, progress and human review speak the same visual language.', flowLabel: 'Onboarding progress', steps: [{ label: 'Import', detail: 'Originals preserved' }, { label: 'Organize', detail: 'Content extracted' }, { label: 'Review', detail: 'Your confirmation' }, { label: 'Create records', detail: 'After review' }],
  sourcesTitle: 'Source library', sourcesCaption: 'SOURCE LIBRARY', sourceCount: '3 sample sources', filterLabel: 'Filter source status', all: 'All', pending: 'To review', completed: 'Organized', searchLabel: 'Find sources', searchPlaceholder: 'Search name or format…', files: [{ id: 'catalog', name: 'Spring & summer catalog.pdf', detail: '12 pages · 3.8 MB · Products', format: 'PDF', status: 'To review' }, { id: 'company', name: 'Company & manufacturing.docx', detail: '6 pages · 860 KB · Company', format: 'DOCX', status: 'Organized' }, { id: 'pricing', name: 'Specifications & pricing.xlsx', detail: '3 sheets · 128 KB · Commercial', format: 'XLSX', status: 'Organized' }],
  view: 'View', noResults: 'No matching sources', noResultsHint: 'Try another keyword or source status.', reset: 'Reset filters', reviewEyebrow: 'HUMAN REVIEW', reviewTitle: 'The final judgment is yours.', reviewText: 'This lightweight cotton-linen fabric is intended for everyday apparel. Composition, weight and supply specifications have been extracted and await comparison with the original.', citation: 'Product catalog.pdf · Page 4 · Sample citation', reviewNote: 'Review confirms the text was checked. It does not certify facts or publish content.', approve: 'Confirm content', needsInput: 'Needs more detail', approved: 'Reviewed', needsInputStatus: 'Needs input', undo: 'Review again', reviewApprovedToast: 'Sample reviewed. No enterprise data was changed.', reviewInputToast: 'Sample marked as needing more detail.',
  productTitle: 'Give information a sense of craft', productDescription: 'Product cards, details and activity records work alone or together.', productCategory: 'MATERIAL COLLECTION', productName: 'Cotton Linen · CL—021', productText: 'Natural texture, a softer touch. Specifications, sources and status come together in one considered card.', productStatus: 'Draft', productMaterial: 'Composition', productMaterialValue: 'Cotton / linen', productWeight: 'Weight', productWeightValue: '180 g/m²', productCode: 'Collection', productCodeValue: 'ESSENTIAL', materialArt: 'Illustrative material swatches, not a real product photograph', materialArtLabel: 'MATERIAL STUDY — 021', materialArtFoot: 'SAGE / SAND / STONE', productOpen: 'View product', save: 'Save sample', saved: 'Saved',
  activityTitle: 'Recent activity', activityCaption: 'ACTIVITY', activityLabel: 'Sample activity history', activities: [{ title: 'Catalog organized', detail: 'Basic information extracted for 8 products', time: '14:32' }, { title: 'Awaiting human review', detail: '3 specifications need a source check', time: '14:28' }, { title: 'Company sources imported', detail: 'Original files and folders preserved', time: '14:20' }], emptyTitle: 'Room for your next idea', emptyText: 'A clear source is the beginning of a good product.', emptyAction: 'Create a sample draft', createdTitle: 'Your sample draft', createdText: 'Draft state is shown. Reload the preview to reset.',
  foundationsTitle: 'Consistent details. Flexible combinations.', foundationsDescription: 'Considered sizing, clear states and quiet feedback keep interactions natural.', buttonsTitle: 'Action buttons', buttonsCaption: 'ACTIONS', primary: 'Primary action', secondary: 'Secondary action', quiet: 'Quiet action', loading: 'Processing', disabled: 'Unavailable', actionToast: 'Component interaction only. No business action was sent.', statusesTitle: 'A language for status', statusesCaption: 'STATUS', neutral: 'Draft', success: 'Complete', warning: 'To confirm', info: 'Processing', danger: 'Retry needed', fieldsTitle: 'Confidence in every input', fieldsCaption: 'FORM FIELDS', fieldName: 'Product name', fieldPlaceholder: 'e.g. Lightweight cotton linen', fieldHint: 'Choose a clear name that is easy to find.', fieldEmail: 'Contact email', fieldEmailPlaceholder: 'name@company.com', emailError: 'Enter a complete email address, such as name@company.com.', footer: 'FORM — Calm, clear interfaces for real work.', footerNote: 'All data is illustrative. No enterprise records are connected.', close: 'Close', dialogTitle: 'Sample details', dialogNote: 'This is a component preview. Product pages supply real content and actions.', dialogSourceText: 'Sources retain their original folders. This view can present full content, citations, page numbers and processing history.',
}
