/** Reviewed content editor shared by primary and translated website drafts. */
import { Button } from '@deepseek-ai/dsh-client-ui-primitives'
import type { PropsLocale } from '@deepseek-ai/dsh-client-ui-slots'
import type { SiteCompanyContent } from './site-company-schema.ts'

/** Edit public facts and evidence-backed editorial pages before generating a revision.
 * @param props - Reviewed content, locale and replacement callback.
 * @returns Accessible content controls with no private enterprise records.
 */
export function SiteContentEditor({ content, onChange, t }: PropsLocale<'sites'> & { content: SiteCompanyContent; onChange: (value: SiteCompanyContent) => void }) {
  return <div className="site-content-fields">
    {(['name', 'description', 'business', 'email', 'phone', 'address'] as const).map(key => <label key={key}>{t(`content_${key}`)}<textarea rows={key === 'description' ? 3 : 1} value={content[key]} onChange={event => onChange({ ...content, [key]: event.target.value })} /></label>)}
    <label>{t('content_qualifications')}<textarea value={content.qualifications.join('\n')} onChange={event => onChange({ ...content, qualifications: event.target.value.split('\n').filter(Boolean) })} /></label>
    {content.products.map((product, index) => <details key={product.slug}><summary>{product.name}</summary>{(['name', 'description'] as const).map(key => <label key={key}>{t(`content_${key}`)}<textarea value={product[key]} onChange={event => onChange({ ...content, products: content.products.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item) })} /></label>)}{(['applications', 'customers', 'differences', 'limitations'] as const).map(key => <label key={key}>{t(`content_${key}`)}<textarea value={product[key].join('\n')} onChange={event => onChange({ ...content, products: content.products.map((item, i) => i === index ? { ...item, [key]: event.target.value.split('\n').filter(Boolean) } : item) })} /></label>)}{product.specifications.map((fact, i) => <div key={i} className="ent-actions"><input aria-label={t('content_specName')} value={fact.name} onChange={event => onChange({ ...content, products: content.products.map((item, n) => n === index ? { ...item, specifications: item.specifications.map((value, j) => j === i ? { ...value, name: event.target.value } : value) } : item) })} /><input aria-label={t('content_specValue')} value={fact.value} onChange={event => onChange({ ...content, products: content.products.map((item, n) => n === index ? { ...item, specifications: item.specifications.map((value, j) => j === i ? { ...value, value: event.target.value } : value) } : item) })} /></div>)}</details>)}
    <h4>{t('content_pages')}</h4><p>{t('content_pagesHelp')}</p>
    {content.pages.map((page, index) => <fieldset key={index}><legend>{t(`page_${page.kind}`)}</legend><label>{t('content_pageKind')}<select value={page.kind} onChange={event => onChange({ ...content, pages: content.pages.map((item, i) => i === index ? { ...item, kind: event.target.value as typeof page.kind } : item) })}>{(['industry', 'solution', 'case', 'comparison'] as const).map(kind => <option key={kind} value={kind}>{t(`page_${kind}`)}</option>)}</select></label>{(['slug', 'title', 'summary'] as const).map(key => <label key={key}>{t(`content_${key}`)}<input value={page[key]} onChange={event => onChange({ ...content, pages: content.pages.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item) })} /></label>)}
      {page.sections.map((section, sectionIndex) => <div key={sectionIndex}><label>{t('content_title')}<input value={section.title} onChange={event => onChange({ ...content, pages: content.pages.map((item, i) => i === index ? { ...item, sections: item.sections.map((value, j) => j === sectionIndex ? { ...value, title: event.target.value } : value) } : item) })} /></label><label>{t('content_body')}<textarea rows={5} value={section.body} onChange={event => onChange({ ...content, pages: content.pages.map((item, i) => i === index ? { ...item, sections: item.sections.map((value, j) => j === sectionIndex ? { ...value, body: event.target.value } : value) } : item) })} /></label></div>)}
      <label>{t('content_sources')}<textarea value={page.sources.map(source => `${source.title} | ${source.url}`).join('\n')} onChange={event => onChange({ ...content, pages: content.pages.map((item, i) => i === index ? { ...item, sources: event.target.value.split('\n').filter(Boolean).map(line => { const divider = line.indexOf('|'); return { title: divider < 0 ? line : line.slice(0, divider).trim(), url: divider < 0 ? '' : line.slice(divider + 1).trim() } }) } : item) })} /></label><Button onClick={() => onChange({ ...content, pages: content.pages.filter((_, i) => i !== index) })}>{t('content_removePage')}</Button>
    </fieldset>)}
    <Button disabled={content.pages.length >= 50} onClick={() => onChange({ ...content, pages: [...content.pages, { kind: 'solution', slug: '', title: '', summary: '', sections: [{ title: '', body: '' }], sources: [] }] })}>{t('content_addPage')}</Button>
  </div>
}
