/** Private site setup, analytics and independently labeled GEO evidence. */
import { useEffect, useRef, useState } from 'react'
import { z } from 'zod'
import { Button } from '@deepseek-ai/dsh-client-ui-primitives'
import type { PropsLocale } from '@deepseek-ai/dsh-client-ui-slots'
import { siteOperationsReport, siteOperationsSettings } from './site-operations-schema.ts'
import { siteCompanyContent, siteCompanyReview } from './site-company-schema.ts'
import { siteGrowth } from './site-growth-schema.ts'
import { suggestCompanyPages } from './site-company-pages.ts'
import { SiteContentEditor } from './client-site-content.tsx'

const draftParameters = z.object({ content: siteCompanyContent, style: z.enum(['industrial', 'precision', 'international']), inquiryEndpoint: z.literal('local'), growth: siteGrowth, sourceDigest: z.string().optional(), locale: z.enum(['en', 'zh-CN']).default('en'), translations: z.array(z.object({ locale: z.enum(['en', 'zh-CN']), content: siteCompanyContent })).default([]) })
const draftResponse = z.object({ revisionId: z.string(), sourceEdited: z.boolean(), parameters: z.unknown(), agentAvailable: z.boolean(), sourceChanged: z.boolean(), review: siteCompanyReview.nullable() })

/** Configure a saved company website and inspect server-owned operation receipts.
 * @param props - Authorized website, locale, saved-revision callback and replacement lock for unsaved edits or requests.
 * @returns Site setup and monitoring controls.
 */
export function SiteOperationsPanel({ siteId, t, disabled, saved, mode, pendingChanged }: PropsLocale<'sites'> & { siteId: string; disabled: boolean; mode: 'content' | 'traffic'; saved: (revisionId: string) => void; pendingChanged: (pending: boolean) => void }) {
  const [report, setReport] = useState<z.infer<typeof siteOperationsReport>>()
  const [settings, setSettings] = useState(siteOperationsSettings.parse({}))
  const [settingsBase, setSettingsBase] = useState<Pick<z.infer<typeof siteOperationsReport>, 'settings' | 'version'>>()
  const [draft, setDraft] = useState<z.infer<typeof draftResponse>>()
  const [parameters, setParameters] = useState<z.infer<typeof draftParameters>>()
  const [savedParameters, setSavedParameters] = useState<z.infer<typeof draftParameters>>()
  const [autoAnalytics, setAutoAnalytics] = useState(false)
  const [refreshSource, setRefreshSource] = useState(false)
  const [confirmed, setConfirmed] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(false)
  const [done, setDone] = useState(false)
  const [retrying, setRetrying] = useState<string>()
  const [question, setQuestion] = useState('')
  const [days, setDays] = useState('30')
  const [citation, setCitation] = useState({ engine: '', question: '', answer: '', evidenceUrl: '', citedUrls: '', observedAt: '' })
  const lifetime = useRef(new AbortController())
  const settingsLoaded = useRef(false)
  const dirty = mode === 'content' ? Boolean(parameters && (parameters !== savedParameters || autoAnalytics || refreshSource)) : Boolean(settingsBase && JSON.stringify(settings) !== JSON.stringify(settingsBase.settings))
  useEffect(() => { pendingChanged(dirty || busy); return () => pendingChanged(false) }, [dirty, busy, pendingChanged])
  useEffect(() => { setConfirmed(false); setDone(false) }, [parameters, autoAnalytics, refreshSource])
  useEffect(() => { const controller = new AbortController(); lifetime.current = controller; return () => controller.abort() }, [])
  const request = async (action: string, body?: unknown) => {
    const response = await fetch(`/api/enterprise/sites?${new URLSearchParams({ siteId, action, days })}`, { signal: lifetime.current.signal, method: body === undefined ? 'GET' : 'POST', ...(body === undefined ? {} : { headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) })
    if (!response.ok) throw new Error('Site operation failed')
    return response.json() as Promise<unknown>
  }
  const loadReport = async (replaceSettings = false) => { const next = siteOperationsReport.parse(await request('ops-report')); if (!lifetime.current.signal.aborted) { setReport(next); if (!settingsLoaded.current || replaceSettings) { setSettings(next.settings); setSettingsBase(next); settingsLoaded.current = true } } }
  useEffect(() => { void loadReport().catch(() => { if (!lifetime.current.signal.aborted) setError(true) }) }, [days])
  const act = async (run: () => Promise<void>) => { if (busy || disabled) return; setBusy(true); setError(false); setDone(false); try { await run(); if (!lifetime.current.signal.aborted) setDone(true) } catch { if (!lifetime.current.signal.aborted) setError(true) } finally { if (!lifetime.current.signal.aborted) setBusy(false) } }
  return <section className="site-hosting site-operations"><h3>{t(mode === 'content' ? 'opsSetup' : 'opsTraffic')}</h3><p>{t(mode === 'content' ? 'contentPanelHelp' : 'trafficPanelHelp')}</p>{error && <p role="alert">{t('opsError')}</p>}{done && <p role="status">{t('opsDone')}</p>}
    {dirty && <div className="ent-notice"><p role="status">{t('unsaved')}</p><Button disabled={busy || disabled} onClick={() => { setParameters(savedParameters); if (report) { setSettings(report.settings); setSettingsBase(report) } setAutoAnalytics(false); setRefreshSource(false); setConfirmed(false); setError(false); setDone(false) }}>{t('discard')}</Button></div>}
    {report?.sourceChanged && <p role="status">{t('opsSourceChanged')}</p>}
    {mode === 'content' && <fieldset disabled={busy || disabled}><legend>{t('opsSetup')}</legend><Button disabled={dirty} onClick={() => { void act(async () => { const value = draftResponse.parse(await request('ops-content')); setDraft(value); const parsed = draftParameters.safeParse(value.parameters); setParameters(parsed.success ? parsed.data : undefined); setSavedParameters(parsed.success ? parsed.data : undefined); setAutoAnalytics(false); setRefreshSource(false); setConfirmed(false) }) }}>{t('opsLoad')}</Button>
      {draft && <>{draft.sourceEdited && <p>{t('opsManual')}</p>}{draft.sourceChanged && <p role="status">{t('opsSourceChanged')}</p>}{parameters && !draft.sourceEdited && <>
        <label>{t('opsLanguage')}<select value={parameters.locale} onChange={event => { setParameters({ ...parameters, locale: event.target.value as 'en' | 'zh-CN', translations: [] }); setConfirmed(false) }}><option value="en">{t('languageEnglish')}</option><option value="zh-CN">{t('languageChinese')}</option></select></label>
        <label>{t('templateStyle')}<select value={parameters.style} onChange={event => setParameters({ ...parameters, style: event.target.value as typeof parameters.style })}>{(['industrial', 'precision', 'international'] as const).map(style => <option key={style} value={style}>{t(style)}</option>)}</select></label>
        <label><input type="checkbox" checked={parameters.growth.agent} disabled={!draft.agentAvailable} onChange={event => setParameters({ ...parameters, growth: { ...parameters.growth, agent: event.target.checked } })} />{t('enableAgent')}</label>
        <label><input type="checkbox" checked={autoAnalytics} disabled={!report?.configured.analytics} onChange={event => setAutoAnalytics(event.target.checked)} />{t('opsAutoAnalytics')}</label>
        {!report?.configured.analytics && <p>{t('opsServiceSetup')}</p>}
        {parameters.growth.analytics && <Button onClick={() => setParameters({ ...parameters, growth: { agent: parameters.growth.agent } })}>{t('opsDisconnectAnalytics')}</Button>}
        <details><summary>{t('opsPublicContent')}</summary><Button disabled={!parameters.content.products.length} onClick={() => { setParameters({ ...parameters, content: suggestCompanyPages(parameters.content, parameters.locale) }); setConfirmed(false) }}>{t('opsSuggestPages')}</Button><SiteContentEditor content={parameters.content} t={t} onChange={content => { setParameters({ ...parameters, content }); setConfirmed(false); setRefreshSource(false) }} /></details>
        {draft.review?.content && <label><input type="checkbox" checked={refreshSource} onChange={event => { setRefreshSource(event.target.checked); setConfirmed(false); if (event.target.checked && draft.review?.content) setParameters({ ...parameters, content: { ...draft.review.content, pages: parameters.content.pages }, translations: [] }) }} />{t('opsRefreshSource')}</label>}
        <details><summary>{t('opsTranslation')}</summary><p>{t('opsTranslationHelp')}</p><Button disabled={!draft.agentAvailable} onClick={() => { void act(async () => { const locale = parameters.locale === 'en' ? 'zh-CN' : 'en'; const translated = siteCompanyContent.parse(await request('ops-translate', { content: parameters.content, locale })); setParameters({ ...parameters, translations: [{ locale, content: translated }] }); setConfirmed(false) }) }}>{t('opsTranslate')}</Button><Button onClick={() => { setParameters({ ...parameters, translations: [{ locale: parameters.locale === 'en' ? 'zh-CN' : 'en', content: structuredClone(parameters.content) }] }); setConfirmed(false) }}>{t('opsManualTranslation')}</Button>{parameters.translations.map(translation => <div key={translation.locale}><h4>{t(translation.locale === 'en' ? 'languageEnglish' : 'languageChinese')}</h4><SiteContentEditor t={t} content={translation.content} onChange={content => { setParameters({ ...parameters, translations: [{ ...translation, content }] }); setConfirmed(false) }} /><Button onClick={() => setParameters({ ...parameters, translations: [] })}>{t('opsRemoveTranslation')}</Button></div>)}</details>
        <label><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />{t('companyConfirm')}</label><Button variant="primary" disabled={!confirmed} onClick={() => { void act(async () => { const result = z.object({ id: z.string() }).parse(await request('ops-draft', { revisionId: draft.revisionId, parameters, refreshSource, sourceDigest: draft.review?.digest, autoAnalytics, confirmed: true })); setDraft(undefined); saved(result.id) }) }}>{t('opsSaveDraft')}</Button>
      </>}</>}
    </fieldset>}
    {mode === 'traffic' && <><div className="site-toolbar"><label>{t('opsPeriod')}<select value={days} onChange={event => setDays(event.target.value)}>{['7', '30', '90'].map(value => <option key={value} value={value}>{t('opsDays', { count: value })}</option>)}</select></label><Button disabled={busy || disabled} onClick={() => { void act(loadReport) }}>{t('opsRefresh')}</Button></div>
    {report?.traffic ? <><dl className="site-metrics">{([['opsPageviews', report.traffic.pageviews], ['opsVisitors', report.traffic.visitors], ['opsVisits', report.traffic.visits], ['opsInquiries', report.inquiries]] as const).map(([key, value]) => <div key={key}><dt>{t(key)}</dt><dd>{value}</dd></div>)}</dl><p>{t('opsRatio')}: {report.traffic.visits ? `${(report.inquiries / report.traffic.visits * 100).toFixed(1)}%` : t('opsUnavailable')}</p><p>{t('opsRatioHelp')}</p><div className="site-metric-tables">{(['sources', 'events'] as const).map(kind => <table key={kind}><caption>{t(kind === 'sources' ? 'opsSources' : 'opsEvents')}</caption><thead><tr><th>{t('opsName')}</th><th>{t('opsCount')}</th></tr></thead><tbody>{report.traffic![kind].map(item => <tr key={item.x}><td>{item.x || t('opsDirect')}</td><td>{item.y}</td></tr>)}</tbody></table>)}</div></> : <p>{t(report?.trafficError ? 'opsTrafficError' : report?.analyticsConnected ? 'opsTrafficCredentials' : 'analyticsMissing')}</p>}
    <details className="site-secondary-options"><summary>{t('opsAutomation')}</summary>{report && <fieldset disabled={busy || disabled}><legend>{t('opsAutomation')}</legend>{(['notifications', 'crm'] as const).map(channel => <label key={channel}><input type="checkbox" disabled={!report.configured[channel]} checked={settings[channel]} onChange={event => setSettings({ ...settings, [channel]: event.target.checked })} />{t(channel === 'crm' ? 'opsCrm' : 'opsNotify')}</label>)}<p>{t('opsDeliveryHelp')}</p>
      <label><input type="checkbox" disabled={!report.configured.search} checked={settings.monitor.enabled} onChange={event => setSettings({ ...settings, monitor: { ...settings.monitor, enabled: event.target.checked } })} />{t('opsMonitor')}</label><label>{t('opsQueries')}<textarea rows={3} value={settings.monitor.queries.join('\n')} onChange={event => setSettings({ ...settings, monitor: { ...settings.monitor, queries: event.target.value.split('\n') } })} /></label><label>{t('opsInterval')}<input type="number" min={1} max={720} value={settings.monitor.intervalHours} onChange={event => setSettings({ ...settings, monitor: { ...settings.monitor, intervalHours: Number(event.target.value) } })} /></label>
      <Button onClick={() => { void act(async () => { await request('ops-configure', { expectedVersion: settingsBase?.version, settings: { ...settings, monitor: { ...settings.monitor, queries: settings.monitor.queries.filter(value => value.trim()) } } }); await loadReport(true) }) }}>{t('opsSaveSettings')}</Button><Button disabled={!report.configured.search || !report.settings.monitor.queries.length} onClick={() => { void act(async () => { await request('ops-monitor', {}); await loadReport() }) }}>{t('opsCheckNow')}</Button>
    </fieldset>}</details>
    <details className="site-secondary-options"><summary>{t('opsAdvanced')}</summary>
    <details><summary>{t('opsCitation')}</summary><p>{t('opsEvidenceHelp')}</p><fieldset disabled={busy || disabled}>{(['engine', 'question', 'answer', 'evidenceUrl', 'citedUrls', 'observedAt'] as const).map(key => <label key={key}>{t(`citation_${key}`)}{key === 'observedAt' ? <input type="datetime-local" value={citation[key]} onChange={event => setCitation({ ...citation, [key]: event.target.value })} /> : <textarea value={citation[key]} rows={key === 'answer' ? 4 : 1} onChange={event => setCitation({ ...citation, [key]: event.target.value })} />}</label>)}<Button onClick={() => { void act(async () => { await request('ops-citation', { ...citation, observedAt: new Date(citation.observedAt).toISOString(), citedUrls: citation.citedUrls.split('\n').filter(Boolean) }); await loadReport() }) }}>{t('opsRecord')}</Button></fieldset></details>
    <details><summary>{t('opsEvaluate')}</summary><p>{t('opsEvaluateHelp')}</p><label>{t('citation_question')}<textarea value={question} maxLength={2000} onChange={event => setQuestion(event.target.value)} /></label><Button disabled={busy || disabled || !question.trim()} onClick={() => { void act(async () => { try { await request('ops-evaluate', { question }) } finally { await loadReport() } }) }}>{t('opsRunEvaluation')}</Button></details>
    <h4>{t('opsObservations')}</h4><p>{t('opsRetention')}</p>{report?.observations.map(item => <article className="site-publish-review" key={item.id}><strong>{t(`evidence_${item.kind}`)}</strong><time> · {new Date(item.createdAt).toLocaleString()}</time><p>{String(item.data.query ?? item.data.question ?? '')}</p>{typeof item.data.status === 'string' && <p>{t(item.data.status === 'failed' ? 'opsCheckFailed' : item.data.status === 'partial' ? 'opsCheckPartial' : 'opsCheckComplete')}</p>}{typeof item.data.answer === 'string' && <p>{item.data.answer}</p>}{Array.isArray(item.data.matches) && <ul>{item.data.matches.map((value, index) => { const match = z.object({ url: z.string(), title: z.string(), position: z.number() }).safeParse(value); return match.success ? <li key={index}>{match.data.position}. <a href={match.data.url} target="_blank" rel="noreferrer">{match.data.title}</a></li> : null })}</ul>}{typeof item.data.evidenceUrl === 'string' && <a href={item.data.evidenceUrl} target="_blank" rel="noreferrer">{t('opsEvidenceLink')}</a>}{item.kind === 'model' && <p>{z.object({ answer: z.string() }).safeParse(item.data.result).data?.answer ?? t('opsCheckFailed')} · {t('opsLatency', { count: String(item.data.durationMs ?? '') })}</p>}<Button disabled={busy || disabled} onClick={() => { void act(async () => { await request('ops-delete-observation', { id: item.id }); await loadReport() }) }}>{t('opsDeleteEvidence')}</Button></article>)}
    <h4>{t('opsCrawlers')}</h4><p>{t('opsCrawlersHelp')}</p><ul>{report?.crawlers.map(item => <li key={`${item.day}:${item.crawler}`}>{item.day} · {item.crawler}: {item.requests}</li>)}</ul>
    <h4>{t('opsDeliveries')}</h4>{report?.deliveries.map(item => <p key={`${item.inquiryId}:${item.channel}`}><code>{item.inquiryId}</code> · {t(item.channel === 'crm' ? 'opsCrm' : 'opsNotify')} · {t(item.state === 'delivered' ? 'opsDelivered' : 'opsDeliveryUnknown')}{item.state !== 'delivered' && <><Button disabled={busy || disabled} onClick={() => setRetrying(`${item.inquiryId}:${item.channel}`)}>{t('opsRetry')}</Button>{retrying === `${item.inquiryId}:${item.channel}` && <><span>{t('opsRetryHelp')}</span><Button disabled={busy || disabled} onClick={() => { void act(async () => { await request('ops-retry', { id: item.inquiryId, channel: item.channel, confirmed: true }); setRetrying(undefined); await loadReport() }) }}>{t('opsRetryConfirm')}</Button></>}</>}{item.state !== 'delivered' && item.channel === 'crm' && <Button disabled={busy || disabled} onClick={() => { void act(async () => { await request('ops-reconcile', { id: item.inquiryId }); await loadReport() }) }}>{t('opsReconcile')}</Button>}</p>)}
    </details></>}
  </section>
}
