/** Validated enterprise records shared by the HTTP producer and browser consumer. */
import { z } from 'zod'
import { taskSchema } from './tasks-schema.ts'
import { approvalSchema } from './governance.ts'
import { geoRecord, geoProgress } from './geo-schema.ts'
import { opportunitySchema } from './opportunities-schema.ts'
import { supplierNodeId } from './supplier.ts'

/** Private file ids are generated by the Host; client filenames never address disk paths. */
export const fileId = z.string().uuid().brand<'EnterpriseFileId'>()
/** Stable identifier for the canonical company entity. */
export const companyEntityId = z.string().regex(/^cmp_[A-Za-z0-9]+$/).brand<'CompanyEntityId'>()
export const claimStatus = z.enum(['VERIFIED', 'SELF_DECLARED', 'INFERRED', 'UNKNOWN', 'OUTDATED', 'CONFLICTED'])
export const visibility = z.enum(['PUBLIC', 'AGENT', 'WORKSPACE', 'RESTRICTED'])
const factSchema = z.object({
  value: z.unknown(), status: claimStatus.default('SELF_DECLARED'), visibility: visibility.default('WORKSPACE'),
  source: z.object({ type: z.string(), uri: z.string().nullable().optional() }).optional(),
  updatedAt: z.iso.datetime().optional(), validUntil: z.iso.datetime().nullable().optional(),
}).strict()
const capabilitySchema = z.object({ status: z.enum(['AVAILABLE', 'UNAVAILABLE', 'REQUIRES_HUMAN', 'REQUIRES_APPROVAL', 'PLANNED', 'UNKNOWN']), interface: z.unknown().optional() }).strict()
/** Editable profile fields; an empty name cannot create an enterprise. */
export const profileSchema = z.object({
  companyEntityId: companyEntityId.optional(),
  schemaVersion: z.string().default('1.0'),
  name: z.string().trim().min(1).max(160),
  kind: z.enum(['enterprise', 'studio']),
  description: z.string().max(5000),
  business: z.string().max(3000),
  website: z.union([z.literal(''), z.url().refine(value => ['http:', 'https:'].includes(new URL(value).protocol))]),
  contact: z.string().max(160),
  email: z.union([z.literal(''), z.email()]),
  phone: z.string().max(100),
  address: z.string().max(1000),
  logoId: fileId.nullable(),
  media: z.object({ coverId: fileId.nullable(), nodeImages: z.record(supplierNodeId, fileId) }).strict().optional(),
  identity: z.object({ canonicalName: z.string().optional(), alternateNames: z.array(z.string()).default([]), legalName: z.string().optional(), tradingName: z.string().optional(), primaryType: z.string().optional(), secondaryTypes: z.array(z.string()).default([]), industry: z.array(z.string()).default([]), foundedYear: z.number().int().min(1).max(9999).nullable().optional(), domains: z.array(z.string()).default([]), sameAs: z.array(z.string()).default([]), headquarters: z.record(z.string(), z.string()).default({}), officialContacts: z.object({ email: z.array(z.string()).default([]), telephone: z.array(z.string()).default([]) }).default({ email: [], telephone: [] }) }).default({ alternateNames: [], secondaryTypes: [], industry: [], domains: [], sameAs: [], headquarters: {}, officialContacts: { email: [], telephone: [] } }),
  offerings: z.record(z.string(), z.unknown()).default({}),
  fit: z.record(z.string(), z.unknown()).default({}),
  capabilities: z.record(z.string(), z.record(z.string(), capabilitySchema)).default({}),
  constraints: z.record(z.string(), z.unknown()).default({}),
  trust: z.object({ claims: z.array(factSchema).default([]), certifications: z.array(z.unknown()).default([]), evidenceSources: z.array(z.unknown()).default([]), verification: z.object({ overallStatus: z.string().default('UNKNOWN') }).default({ overallStatus: 'UNKNOWN' }), lastReviewedAt: z.iso.datetime().nullable().default(null) }).default({ claims: [], certifications: [], evidenceSources: [], verification: { overallStatus: 'UNKNOWN' }, lastReviewedAt: null }),
}).strict()
/** Durable enterprise profile. */
export type Profile = z.infer<typeof profileSchema>
/** Public metadata excludes private paths. */
export const fileSchema = z.object({
  id: fileId, name: z.string(), mime: z.string(), size: z.number(), createdAt: z.string(),
  category: z.enum(['image', 'video', 'document']),
  knowledgeStatus: z.enum(['ready', 'unsupported', 'empty', 'failed']),
})
/** Uploaded asset metadata. */
export type Asset = z.infer<typeof fileSchema>
/** One fresh server view is returned after every successful mutation. */
export const snapshotSchema = z.object({
  profile: profileSchema.nullable(),
  submittedAt: z.iso.datetime().nullable(),
  files: z.array(fileSchema),
  maxFileBytes: z.number(),
  tasks: z.array(taskSchema),
  approvals: z.array(approvalSchema),
  geo: z.array(geoRecord).default([]),
  opportunities: z.array(opportunitySchema).default([]),
  onboarding: geoProgress,
})
/** Enterprise view loaded at mount and refreshed after mutations. */
export type Snapshot = z.infer<typeof snapshotSchema>
/** Names are labels, never filesystem paths or response header fragments. */
export const filenameSchema = z.string().trim().min(1).max(240).refine(value => !/[\x00-\x1f\x7f/\\]/.test(value))
