/** Editable English manufacturing starter; company facts and imagery are explicitly illustrative. */
import { readFileSync } from 'node:fs'
import type { SiteProject, SiteProjectFile } from '../../../packages/site/site/src/types.ts'
import type { ManufacturingParameters } from './site-template-provider.ts'

const directory = new URL('../templates/manufacturing/', import.meta.url)
const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)

/** Generate an English manufacturing project from validated content and design parameters.
 * @param parameters - Provider-resolved input with explicit brand and style.
 * @returns Complete local source and illustrative assets.
 */
export function manufacturingProject(parameters: ManufacturingParameters): SiteProject {
  const brand = `<span class="brand-mark" aria-hidden="true"><i></i><i></i></span><span>${escape(parameters.brandName.toUpperCase())}<small>${escape(parameters.tagline)}</small></span>`
  const links = [['Products', '/products/'], ['Applications', '/applications/'], ['Quality', '/quality/'], ['About us', '/about/']] as const
  const arrow = '<span aria-hidden="true">↗</span>'
  const button = (label: string, href: string, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${href}">${label}${arrow}</a>`
  const productImage = (position: string, label: string) => `<div class="product-image ${position}" role="img" aria-label="Illustrative ${label}"></div>`
  const sampleProducts = [
    { slug: 'shaft-couplings', title: 'Shaft couplings', type: 'ROTARY MOTION', image: 'coupling', summary: 'Connect the drive to the application. Define the shaft interface, alignment and operating conditions.', detail: 'For drive connections that need a clear specification.', options: ['Bore and shaft interface', 'Mounting arrangement', 'Torque and speed requirements', 'Material and surface treatment'] },
    { slug: 'linear-guides', title: 'Linear guides', type: 'LINEAR MOTION', image: 'guide', summary: 'Guide controlled movement. Specify the load, travel and mounting envelope for your assembly.', detail: 'Plan linear movement around the load and the installation.', options: ['Rail and carriage arrangement', 'Travel and mounting envelope', 'Load and duty cycle', 'Lubrication and environment'] },
    { slug: 'machined-housings', title: 'Machined housings', type: 'CUSTOM MACHINING', image: 'housing', summary: 'Turn a drawing into a defined component. Align critical features, finish and inspection requirements.', detail: 'Bring critical dimensions and inspection into the same conversation.', options: ['Drawing revision and datums', 'Material specification', 'Critical tolerances and finish', 'Inspection and packing requirements'] },
  ] as const
  const products = (parameters.products ?? sampleProducts.map((product, index) => ({ ...product, category: ['rotary', 'linear', 'machining'][index]! }))).map(product => ({ ...product, title: escape(product.title), type: escape(product.type), summary: escape(product.summary), detail: escape(product.detail), options: product.options.map(escape) }))
  const productCards = () => products.map(product => `<article class="product-card" data-category="${product.category}"><a href="/products/${product.slug}/">${productImage(product.image, product.title)}<div class="product-copy"><span class="eyebrow">${product.type}</span><h3>${product.title}${arrow}</h3><p>${product.summary}</p><span class="text-link">Explore product family</span></div></a></article>`).join('')
  const heading = (eyebrow: string, title: string, description: string) => `<section class="page-heading wrap"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${description}</p></section>`
  const cta = `<section class="cta-band"><div class="wrap cta-inner"><div><span class="eyebrow">LET’S DEFINE THE RIGHT COMPONENT</span><h2>Start with your drawing.<br>Build a clearer specification.</h2></div>${button('Prepare an inquiry', '/contact/')}</div></section>`

  function page(title: string, body: string, active = ''): string {
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | ${escape(parameters.brandName)}</title><meta name="description" content="An illustrative manufacturing website: precision component families, application planning, quality documentation and inquiry preparation."><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/styles.css"><script defer src="/site.js"></script></head><body class="theme-${parameters.style}">
  <a class="skip-link" href="#main">Skip to content</a><div class="utility"><div class="wrap"><span>PRECISION COMPONENTS · OEM SOURCING</span><span>ENGLISH <i aria-hidden="true">/</i> MANUFACTURING DEMO</span></div></div>
  <header class="header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="${escape(parameters.brandName)} home">${brand}</a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">☰</span></button><nav id="primary-nav" aria-label="Main navigation">${links.map(([text, href]) => `<a href="${href}"${active === href ? ' aria-current="page"' : ''}>${text}</a>`).join('')}${button('Request a quote', '/contact/')}</nav></div></header>
  <main id="main">${body}</main><footer class="footer"><div class="wrap footer-grid"><div><a class="brand" href="/">${brand}</a><p>Components specified with care.<br>Manufacturing presented with clarity.</p><p class="demo-label">Illustrative company and product imagery.<br>Replace with approved business information before publication.</p></div><div><h2>Products</h2>${products.map(p => `<a href="/products/${p.slug}/">${p.title}</a>`).join('')}</div><div><h2>Company</h2><a href="/applications/">Applications</a><a href="/quality/">Quality approach</a><a href="/about/">About ${escape(parameters.brandName)}</a></div><div><h2>Your next project</h2><p>Have a drawing or a requirement?<br>Prepare the details for a useful first discussion.</p><a class="footer-contact" href="/contact/">Prepare an inquiry ${arrow}</a></div></div><div class="wrap footer-bottom"><span>© ${escape(parameters.brandName)} · Manufacturing website template</span><a href="/privacy/">Privacy & inquiry information</a></div></footer></body></html>`
  }

  const home = `<section class="hero"><img class="hero-photo" src="/assets/factory.jpg" alt="Illustrative precision machining scene"><div class="hero-shade"></div><div class="wrap hero-content"><p class="eyebrow">FROM DRAWING TO COMPONENT</p><h1>Precision in every part.<br>Clarity in every step.</h1><p>Mechanical components for the assemblies you’re building.<br>Explore the product families. Define what your application needs.</p><div class="hero-actions">${button('Explore our products', '/products/')}${button('Discuss your requirements', '/contact/', true)}</div><span class="image-caption">Illustrative production imagery</span></div><div class="hero-index"><span>01 /</span> ENGINEERING-LED SOURCING</div></section>
<section class="capability-strip wrap" aria-label="Specification priorities"><div><span>01</span><strong>Drawing-led<br>specification</strong></div><div><span>02</span><strong>Application-focused<br>selection</strong></div><div><span>03</span><strong>Defined quality<br>requirements</strong></div><div><span>04</span><strong>Documentation<br>for the next step</strong></div></section>
<section class="section wrap"><div class="section-top"><div><p class="eyebrow">PRODUCT FAMILIES</p><h2>Built into your next solution.</h2></div><a class="text-link" href="/products/">View all products ${arrow}</a></div><div class="product-grid">${productCards()}</div></section>
<section class="application-section"><div class="wrap split-section"><div><p class="eyebrow">APPLICATIONS</p><h2>Start with the way<br>your equipment works.</h2><p class="lead">The right component begins with the load, movement and environment. Bring the application into the specification.</p>${button('Explore applications', '/applications/', true)}</div><div class="application-list"><a href="/applications/#automation"><span>01</span><div><h3>Industrial automation</h3><p>Motion interfaces, positioning and machine assemblies.</p></div>${arrow}</a><a href="/applications/#handling"><span>02</span><div><h3>Material handling</h3><p>Repeatable movement and defined operating conditions.</p></div>${arrow}</a><a href="/applications/#equipment"><span>03</span><div><h3>Custom equipment</h3><p>Drawing-based parts built around your installation.</p></div>${arrow}</a></div></div></section>
<section class="section wrap quality-home"><div class="quality-visual"><img src="/assets/factory.jpg" alt="Illustrative machining equipment"><div class="photo-tag">DETAILS THAT MATTER<br><strong>From specification<br>to verification.</strong></div></div><div><p class="eyebrow">QUALITY & DOCUMENTATION</p><h2>Define the evidence.<br>Not just the part.</h2><p class="lead">Put material, dimensional and documentation requirements into the discussion before an order is placed.</p><ul class="check-list"><li>Drawing revision and critical characteristics</li><li>Material and finish requirements</li><li>Inspection records and shipment documentation</li></ul><a class="text-link" href="/quality/">Our quality approach ${arrow}</a></div></section>${cta}`
  const catalog = `${heading('OUR PRODUCTS', 'Find the right starting point.', 'Explore illustrative component families, then define the specification for your own application.')}<section class="wrap catalog section"><div class="filter-bar" role="group" aria-label="Product category"><button aria-pressed="true" data-filter="all">All products</button><button aria-pressed="false" data-filter="rotary">Rotary motion</button><button aria-pressed="false" data-filter="linear">Linear motion</button><button aria-pressed="false" data-filter="machining">Custom machining</button></div><div class="product-grid catalog-grid">${productCards()}</div><p class="caption">Illustrative components and configuration options. Final specifications require a reviewed drawing and quotation.</p></section>${cta}`
  const applications = `${heading('APPLICATION ENGINEERING', 'Understand the application.<br>Specify the component.', 'A useful technical discussion starts with how the equipment operates, not just a part number.')}<section class="wrap application-details"><article id="automation"><span class="large-number">01</span><div><p class="eyebrow">INDUSTRIAL AUTOMATION</p><h2>Keep movement and interface aligned.</h2><p>Define positioning requirements, mounting interfaces and the machine environment together. A guide assembly and a drive coupling serve different functions within the same system.</p><ul><li>Required motion and operating cycle</li><li>Mounting space and interfaces</li><li>Load, speed and environmental conditions</li></ul><a class="text-link" href="/products/">Explore product families ${arrow}</a></div></article><article id="handling"><span class="large-number">02</span><div><p class="eyebrow">MATERIAL HANDLING</p><h2>Plan for the full operating cycle.</h2><p>Consider starts, stops, load variation and maintenance access. Share the operating context so that assumptions can be resolved during technical review.</p><a class="text-link" href="/products/">Explore product families ${arrow}</a></div></article><article id="equipment"><span class="large-number">03</span><div><p class="eyebrow">CUSTOM EQUIPMENT</p><h2>A drawing creates a shared starting point.</h2><p>Document the features that matter to fit and function. Include material, drawing revision, critical tolerances and the information required at inspection.</p><a class="text-link" href="/products/">Explore product families ${arrow}</a></div></article></section>${cta}`
  const quality = `${heading('QUALITY & DOCUMENTATION', 'Make requirements<br>measurable.', 'Specify which characteristics need verification and what evidence must accompany the component.')}<section class="wrap quality-intro"><img src="/assets/factory.jpg" alt="Illustrative manufacturing scene"><div><p class="eyebrow">A CLEARER QUALITY DISCUSSION</p><h2>Agree the inspection scope<br>before production.</h2><p>Use an approved drawing and an agreed inspection plan to connect design intent with acceptance criteria. The following workflow is illustrative, not a claim of certification.</p><a class="text-link" href="/contact/">Discuss documentation requirements ${arrow}</a></div></section><section class="section wrap"><div class="section-top"><div><p class="eyebrow">THE REVIEW PROCESS</p><h2>Four points of alignment.</h2></div></div><div class="process-grid">${[['01','Requirements review','Identify the drawing revision, materials, critical features and order conditions.'],['02','Inspection planning','Agree methods, sampling, acceptance criteria and any required records.'],['03','Verification records','Document the agreed checks and review discrepancies before release.'],['04','Delivery documentation','Confirm packaging, identification and required documents for the shipment.']].map(([n,title,text])=>`<article><span>${n}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><aside class="notice"><strong>Certificates and supporting documents</strong><p>No certifications are claimed in this sample. Add only current, approved certificates with an identifiable issuer, scope and validity period.</p></aside></section>${cta}`
  const about = `${heading('ABOUT ' + escape(parameters.brandName.toUpperCase()), 'Good manufacturing relationships<br>start with clear information.', 'An illustrative precision-component brand, built around the way an international buyer evaluates a manufacturing partner.')}<section class="wrap about-intro"><div><p class="eyebrow">OUR FOCUS</p><h2>The component is only<br>part of the conversation.</h2><p>Products, application context, quality requirements and delivery documentation belong together. This template gives each subject a clear place, so buyers can move from an initial question to a useful inquiry.</p><p>Replace this introduction with the company’s approved story, actual manufacturing scope and verifiable operating information.</p></div><img src="/assets/components.jpg" alt="Illustrative precision mechanical components"></section><section class="section wrap"><div class="process-grid about-values"><article><span>01</span><h3>Technical clarity</h3><p>Explain the product family and the information needed to assess suitability.</p></article><article><span>02</span><h3>Relevant evidence</h3><p>Connect business claims to approved documents and actual operating capabilities.</p></article><article><span>03</span><h3>A useful next step</h3><p>Make it easy for the buyer to share requirements without implying an order has been placed.</p></article></div></section>${cta}`
  const contact = `${heading('CONTACT & INQUIRIES', 'Tell us what<br>you’re building.', 'Organize the details for a technical discussion. This demo prepares an inquiry draft; it does not send a message or place an order.')}<section class="wrap contact-grid"><aside><p class="eyebrow">A BETTER FIRST CONVERSATION</p><h2>Start with what<br>you already know.</h2><p>A part reference, an application or a drawing revision is enough to begin defining the requirement.</p><ol class="inquiry-steps"><li><strong>Describe the application</strong><span>What does the component need to do?</span></li><li><strong>Identify the key requirements</strong><span>Material, interfaces, quantity and timing.</span></li><li><strong>Review your inquiry</strong><span>Check the draft before sharing it with a supplier.</span></li></ol><p class="caption">Verified contact details are added when this template is configured for a real company.</p></aside><form id="inquiry-form"><div class="form-row"><label>Your name<input name="name" autocomplete="name" required></label><label>Business email<input type="email" name="email" autocomplete="email" required></label></div><label>Company<input name="company" autocomplete="organization" required></label><div class="form-row"><label>Product interest<select name="product"><option value="General inquiry">Select a product family</option>${products.map(product => `<option value="${product.title}" data-product-slug="${product.slug}">${product.title}</option>`).join('')}</select></label><label>Estimated quantity<input name="quantity" placeholder="e.g. prototype / batch / annual demand"></label></div><label>Project requirements<textarea name="requirements" rows="5" required placeholder="Application, drawing reference, materials, critical dimensions and target timing…"></textarea></label><label class="checkbox-label"><input type="checkbox" required> I have reviewed the <a href="/privacy/">inquiry information</a> and understand this is a local draft.</label><button class="button" type="submit">Prepare inquiry draft ${arrow}</button><p class="caption">Nothing is transmitted by this demonstration form.</p><div id="inquiry-output" hidden><h2>Your inquiry draft</h2><p role="status">Draft prepared. No message has been sent.</p><label>Review and copy the draft<textarea id="inquiry-draft" readonly rows="12"></textarea></label></div></form></section>`
  const privacy = `${heading('PRIVACY & INQUIRY INFORMATION', 'A transparent demonstration.', 'This sample website is an editable manufacturing template, not an operating company or a live sales channel.')}<section class="wrap legal-copy"><h2>Information entered in the inquiry form</h2><p>The form assembles a draft in this page. It does not transmit your details, save them to a server or place an order. Reloading the page clears the draft.</p><h2>Illustrative content</h2><p>${escape(parameters.brandName)}, the component imagery and the manufacturing scene are illustrative. No certification, customer endorsement, production capacity, delivery commitment or product performance is claimed.</p><h2>Before publication</h2><p>The site owner must replace sample information, supply approved business and product facts, configure a real inquiry channel and publish privacy information appropriate to that channel.</p><a class="text-link" href="/contact/">Return to your inquiry ${arrow}</a></section>`
  const files: SiteProjectFile[] = [
    { path: 'index.html', content: page('Precision components for industrial applications', home), encoding: 'utf8' },
    ...[['products/index.html','Products',catalog,'/products/'],['applications/index.html','Applications',applications,'/applications/'],['quality/index.html','Quality & documentation',quality,'/quality/'],['about/index.html','About us',about,'/about/'],['contact/index.html','Request a quote',contact,'/contact/'],['privacy/index.html','Privacy & inquiry information',privacy,'']].map(([path,title,body,active]): SiteProjectFile => ({ path: path!, content: page(title!,body!,active), encoding: 'utf8' })),
    ...products.map(product => ({ path: `products/${product.slug}/index.html`, content: page(product.title, `<div class="wrap breadcrumb"><a href="/">Home</a><span>/</span><a href="/products/">Products</a><span>/</span>${product.title}</div><section class="wrap product-detail">${productImage(product.image,product.title)}<div><p class="eyebrow">${product.type}</p><h1>${product.title}</h1><p class="lead">${product.detail}</p><p>${product.summary}</p><dl>${product.options.map((option,index)=>`<div><dt>0${index+1}</dt><dd>${option}</dd></div>`).join('')}</dl>${button('Discuss this product','/contact/#'+product.slug)}<p class="caption">Illustrative product family. Confirm options and specifications against an approved drawing.</p></div></section><section class="wrap section product-information"><h2>What to include in your inquiry</h2><p>Share the application, drawing or part reference, estimated quantity and required timing. Include the acceptance criteria that matter to your assembly.</p><a class="text-link" href="/quality/">Plan the inspection requirements ${arrow}</a></section>${cta}`,'/products/'), encoding: 'utf8' as const })),
    ...['site.css','styles.css','site.js'].map(path => ({ path, content: readFileSync(new URL(path,directory),'utf8'), encoding: 'utf8' as const })),
    ...['factory.jpg','components.jpg'].map(name => ({ path: `assets/${name}`, content: readFileSync(new URL(name,directory)).toString('base64'), encoding: 'base64' as const })),
  ]
  return { framework: 'static', files }
}
