/** Static introduction and interaction feedback using the shared workspace palette. */
export const siteMotionStyle = `
.site-introduction{padding:24px;border:1px solid var(--dsw-alias-border-l4);border-radius:14px;background:var(--dsw-alias-bg-layer-1);text-align:left}
.site-introduction-heading{display:flex;align-items:flex-start;gap:14px}.site-introduction-icon{display:grid;place-items:center;flex:0 0 42px;height:42px;border-radius:12px;background:color-mix(in srgb,var(--workbench-action,#3655db) 9%,transparent);color:var(--workbench-action,#3655db)}.site-introduction-icon svg{width:24px;height:24px}
.site-welcome .site-introduction h2{margin:0 0 8px;font-size:20px;font-weight:650;line-height:1.35;letter-spacing:-.45px}.site-welcome .site-introduction p{max-width:none;margin:0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.7}
.site-start-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px;list-style:none;padding:21px 0 0;margin:22px 0 0;border-top:1px solid var(--dsw-alias-border-l4)}.site-start-steps li{display:flex;gap:10px}.site-step-number{display:grid;place-items:center;flex:0 0 22px;height:22px;font-size:11px;font-weight:650;border:1px solid var(--dsw-alias-border-l4);border-radius:50%;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);transition:color 160ms ease,border-color 160ms ease,background 160ms ease,transform 160ms ease}.site-start-steps strong{display:block;margin:2px 0 5px;font-size:12px;font-weight:600}.site-welcome .site-start-steps p{font-size:12px;line-height:1.65}
@media(hover:hover){.site-start-steps li:hover .site-step-number{color:var(--workbench-action,#3655db);border-color:color-mix(in srgb,var(--workbench-action,#3655db) 35%,transparent);background:color-mix(in srgb,var(--workbench-action,#3655db) 8%,transparent);transform:translateY(-2px)}}
@media(max-width:760px){.site-introduction{padding:20px}.site-start-steps{grid-template-columns:1fr;gap:16px;margin-top:18px;padding-top:18px}.site-introduction-heading{gap:12px}.site-welcome .site-introduction h2{font-size:19px}}
@media(prefers-reduced-motion:reduce){.site-step-number{transition:none}.site-start-steps li:hover .site-step-number{transform:none}}
`
