/** Public website interface copy; reviewed business facts retain their supplied language. */
export const companyZh: Record<string, string> = {
  "Products": "产品",
  "Applications": "应用",
  "Qualifications": "资质",
  "Company": "企业",
  "Contact": "联系",
  "Buying guide": "采购指南",
  "FAQ": "常见问题",
  "Ask AI": "咨询 AI",
  "View specifications": "查看参数",
  "Home": "首页",
  "Skip to content": "跳转到正文",
  "Menu": "菜单",
  "Tell us what your project needs.": "告诉我们您的项目需求。",
  "Send an inquiry": "发送询盘",
  "Privacy & inquiries": "隐私与询盘",
  "LET’S TALK": "联系我们",
  "Discuss your requirements": "沟通您的需求",
  "Name": "姓名",
  "Email": "邮箱",
  "Product": "产品",
  "General inquiry": "一般咨询",
  "Requirements": "需求",
  "Website": "网站",
  "I agree that my details will be stored so the company can respond.": "我同意企业保存提交的信息，用于回复咨询。",
  "Privacy information": "隐私说明",
  "Send inquiry": "提交询盘",
  "Enable JavaScript to submit your inquiry.": "请启用 JavaScript 以提交询盘。",
  "Online inquiries are not configured. Please use the company contact details.": "在线询盘尚未配置，请通过企业联系方式咨询。",
  "Explore products": "查看产品",
  "Discuss your project": "沟通项目",
  "PRODUCT PORTFOLIO": "产品目录",
  "Explore our products": "了解我们的产品",
  "Contact us for product information.": "请联系我们获取产品信息。",
  "COMPANY": "企业",
  "About our business": "了解企业",
  "APPLICATIONS": "应用",
  "Products for your application": "适用产品与应用",
  "Contact us to discuss suitability for your application.": "请联系我们确认产品是否适合您的应用。",
  "QUALIFICATIONS": "资质",
  "Company qualifications": "企业资质",
  "Contact us for qualification and documentation requests.": "请联系我们获取资质和相关文件。",
  "Our business": "主营业务",
  "Privacy": "隐私",
  "PRIVACY": "隐私",
  "Inquiry information": "询盘信息",
  "PRODUCT": "产品",
  "Specifications": "参数",
  "Inquire about this product": "咨询此产品",
  "Product questions": "产品问答",
  "BUYER QUESTIONS": "采购问答",
  "Product selection guide": "产品选型指南",
  "BUYING GUIDE": "采购指南",
  "Compare requirements with published specifications": "根据公开参数核对需求",
  "Intended customers": "适用客户",
  "Product characteristics": "产品特点",
  "Limitations": "限制条件",
  "Include your application, required specifications and quantity in your inquiry. Price, lead time and suitability require confirmation from the company.": "请在询盘中说明应用、规格和数量。价格、交期及适用性需要企业确认。",
  "Product consultation": "产品咨询",
  "PRODUCT CONSULTATION": "产品咨询",
  "Ask about our products": "咨询我们的产品",
  "Answers use the published company information. Confirm specifications and commercial terms with the company.": "回答基于已发布的企业资料，规格及商务条款请与企业确认。",
  "Your question": "您的问题",
  "Questions and answers are stored privately by the company to provide this consultation. Do not include sensitive information.": "企业会私密保存问答以提供咨询服务，请勿提供敏感信息。",
  "Ask a question": "提问",
  "Prepare an inquiry from this conversation": "将本次对话整理为询盘",
  "Public references": "公开来源",
  "Source": "来源",
  "This website uses self-hosted Umami to measure visits and interactions. Contact the company for its data retention and privacy practices.": "本网站使用自托管 Umami 统计访问和互动。数据保留及隐私规则请联系企业了解。",
  "Industry": "行业",
  "Solution": "解决方案",
  "Case study": "案例",
  "Comparison": "对比",
  "Resources": "资料"
}
