/** Enterprise layout scoped to its root and portaled dialogs; native primitives retain theme tokens. */
export const style = `
.ent-commerce-active .ent-inner > :not(.commerce-surface){display:none}
.ent-commerce-active .ent-inner{max-width:1200px;width:100%}

.ent,.ent-dialog{color:var(--dsw-alias-label-primary);font-size:14px;letter-spacing:0}
.ent{height:100%;min-width:0;overflow:auto;background:var(--dsw-alias-bg-layer-1);padding:32px 36px;box-sizing:border-box}
.ent *,.ent-dialog *{box-sizing:border-box;letter-spacing:0}
.ent-inner{max-width:1080px;margin:0 auto}
.ent-computers .ent-actions{flex-wrap:wrap}.ent-computers .ent-actions>a{width:auto;height:auto;white-space:nowrap}.ent-computers p{line-height:1.6;overflow-wrap:anywhere}.ent-computers .ent-section{padding-top:24px}.ent-computers .ent-task-row>div{min-width:0}
.ent h1{font-size:24px;line-height:32px;margin:0;overflow-wrap:anywhere}.ent h2{font-size:16px;margin:0 0 20px}
.ent-header,.ent-identity,.ent-toolbar,.ent-actions{display:flex;align-items:center;gap:12px}
.ent-header{justify-content:space-between;margin-bottom:28px;flex-wrap:wrap}.ent-identity{min-width:0}.ent-identity>div{min-width:0}
.ent-muted{color:var(--dsw-alias-label-tertiary);font-size:13px;margin:5px 0 0}
.ent-logo{width:56px;height:56px;flex:none;object-fit:contain;border:1px solid var(--dsw-alias-border-l4);border-radius:8px;background:var(--dsw-alias-bg-layer-2);display:grid;place-items:center;color:var(--dsw-alias-brand-primary)}
.ent-tabs{display:flex;gap:28px;border-bottom:1px solid var(--dsw-alias-border-l4);margin-bottom:28px}
.ent-tab{appearance:none;background:none;border:0;border-bottom:2px solid transparent;color:var(--dsw-alias-label-tertiary);padding:12px 0;font:inherit;cursor:pointer;white-space:nowrap}
.ent-tab[aria-selected=true]{color:var(--dsw-alias-brand-primary);border-bottom-color:var(--dsw-alias-brand-primary)}
.ent-section{padding:8px 0 28px;margin-bottom:24px;border-bottom:1px solid var(--dsw-alias-border-l4)}
.ent-status{display:inline-flex;margin:0 0 20px;padding:6px 10px;border-radius:999px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary);font-size:13px}
.ent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px 36px}.ent-field{display:flex;flex-direction:column;gap:8px;min-width:0}.ent-wide{grid-column:1/-1}
.ent-field>span:first-child,.ent-field>dt{color:var(--dsw-alias-label-tertiary);font-size:13px}.ent-field dd{margin:0;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}.ent-field a{color:var(--dsw-alias-brand-primary)}
.ent-form textarea,.ent-form select{width:100%;border:1px solid var(--dsw-alias-border-l4);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:inherit;font:inherit;padding:10px;resize:vertical}.ent-form textarea{min-height:100px}.ent-form input{width:100%}.ent-form .ent-actions{margin-top:24px}
.ent-toolbar{justify-content:space-between;flex-wrap:wrap;margin-bottom:20px}.ent-filters{display:flex;gap:2px;flex-wrap:wrap}.ent-filters button{border:0;background:transparent;color:var(--dsw-alias-label-tertiary);font:inherit;padding:7px 12px;cursor:pointer;border-radius:6px}.ent-filters button[aria-pressed=true]{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}
.ent-files{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px}.ent-file{min-width:0;border:1px solid var(--dsw-alias-border-l4);border-radius:8px;overflow:hidden}.ent-thumb{width:100%;height:148px;border:0;display:flex;align-items:center;justify-content:center;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-tertiary);cursor:pointer;padding:12px}.ent-thumb img,.ent-thumb video{max-width:100%;max-height:100%;object-fit:contain}.ent-file-info{padding:12px}.ent-file-name{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin:0 0 6px}.ent-file .ent-actions{justify-content:flex-end;gap:2px;margin-top:8px}.ent-actions button{flex:none}
.ent-knowledge{font-size:12px;margin:8px 0 0;color:var(--dsw-alias-label-tertiary)}.ent-knowledge-ready{color:var(--dsw-alias-brand-primary)}.ent-knowledge-failed{color:#c24747}
.ent-ai-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.ent-ai-card{border:1px solid var(--dsw-alias-border-l4);border-radius:10px;padding:22px;background:var(--dsw-alias-bg-layer-2)}.ent-ai-card h3{font-size:17px;margin:0 0 10px}.ent-ai-card p{color:var(--dsw-alias-label-secondary);line-height:1.7;min-height:48px;margin:0 0 20px}
.ent-actions a{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;color:var(--dsw-alias-label-primary);border-radius:6px}.ent-actions a:hover{background:var(--dsw-alias-bg-layer-2)}
.ent-empty{min-height:280px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;color:var(--dsw-alias-label-tertiary)}
.ent-notice{padding:12px 16px;border-left:3px solid #c24747;background:var(--dsw-alias-bg-layer-2);margin:0 0 20px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.ent-progress{margin-bottom:20px}.ent-progress progress{width:100%;height:5px;accent-color:var(--dsw-alias-brand-primary)}
.ent-preview{display:block;max-width:100%;max-height:65vh;object-fit:contain;margin:auto}.ent-dialog{max-width:900px;width:calc(100vw - 32px)}.ent-dialog .ent-field{margin:16px 0}.ent-logo-options{display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:12px}.ent-logo-options button{border:1px solid var(--dsw-alias-border-l4);background:transparent;padding:8px;border-radius:6px;cursor:pointer;color:inherit}.ent-logo-options img{width:80px;height:80px;object-fit:contain}.ent-logo-options p{margin:5px 0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
@media(max-width:700px){.ent{padding:22px 16px}.ent-tabs{max-width:100%;gap:16px;overflow-x:auto}.ent-grid,.ent-ai-grid{grid-template-columns:minmax(0,1fr);gap:20px}.ent-wide{grid-column:auto}.ent h1{font-size:21px}.ent-files{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ent-thumb{height:120px}.ent-header{gap:16px}.ent-file-info{padding:9px}.ent-toolbar>span{width:100%}.ent-logo{width:44px;height:44px}.ent-ai-card p{min-height:0}}
@media(max-width:380px){.ent-files{grid-template-columns:minmax(0,1fr)}}
.ent-task-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;padding:18px 0;border-bottom:1px solid var(--dsw-alias-border-l4)}.ent-task-row h3{font-size:16px;margin:0 0 8px;overflow-wrap:anywhere}.ent-task-description{white-space:pre-wrap;overflow-wrap:anywhere;margin:8px 0}.ent-task-row select{max-width:100%;padding:6px;color:inherit;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l4);border-radius:6px}.ent-task-history{padding-left:24px}.ent-task-history li{padding:12px 0;border-bottom:1px solid var(--dsw-alias-border-l4);overflow-wrap:anywhere}@media(max-width:700px){.ent-task-row{grid-template-columns:minmax(0,1fr)}.ent-task-row .ent-actions{flex-wrap:wrap}}
.ent-opportunity-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.ent-opportunity-card{border:1px solid var(--dsw-alias-border-l4);border-radius:10px;padding:20px;background:var(--dsw-alias-bg-layer-2)}.ent-opportunity-card h3{font-size:17px;margin:0 0 6px;overflow-wrap:anywhere}.ent-opportunity-card>p{line-height:1.6;overflow-wrap:anywhere}.ent-opportunity-heading{display:flex;justify-content:space-between;gap:16px}.ent-opportunity-heading>strong{font-size:26px;color:var(--dsw-alias-brand-primary)}.ent-opportunity-card select{padding:6px;color:inherit;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l4);border-radius:6px}.ent-opportunity-detail li{margin:10px 0;overflow-wrap:anywhere}.ent-opportunity-detail p{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:700px){.ent-opportunity-grid{grid-template-columns:minmax(0,1fr)}}
`
