/** Scoped reading, detail and focused editing layouts using the host theme. */
export const supplierExperienceStyle = `
.supplier-panel,.sp-detail,.sp-editor-dialog,.sp-onboarding{--sp-ink:var(--dsw-alias-label-primary);--sp-muted:var(--dsw-alias-label-secondary);--sp-line:var(--dsw-alias-border-l4);--sp-paper:var(--dsw-alias-bg-layer-1);--sp-soft:var(--dsw-alias-bg-layer-2);--sp-accent:var(--dsw-alias-brand-primary);color:var(--sp-ink)}
.supplier-panel button,.sp-detail button,.sp-editor-dialog button{font-family:inherit}
.supplier-panel button:focus-visible,.sp-detail button:focus-visible,.sp-editor-dialog button:focus-visible{outline:2px solid var(--sp-accent);outline-offset:4px}
.sp-kicker{display:block;font-size:11px;font-weight:600;letter-spacing:.08em;line-height:1.6;color:var(--sp-muted)}
.sp-hero{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:32px;border-radius:22px;padding:38px 36px;color:#f4f9f6;background:radial-gradient(ellipse at 85% 10%,#326955 0,transparent 57%),#183d33;overflow:hidden}
.sp-hero .sp-kicker{color:#b7d7c6;letter-spacing:.16em}.ent .sp-hero h2{font-size:clamp(24px,2.5vw,34px);font-weight:600;line-height:1.45;max-width:620px;margin:13px 0 15px;letter-spacing:-.025em}
.sp-hero-copy>p{color:#d0e2d8;font-size:14px;line-height:1.9;max-width:590px;margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.sp-hero-status{display:flex;align-items:center;flex-wrap:wrap;gap:7px;font-size:11px;color:#bbd6c9;margin-top:28px}.sp-dot{width:6px;height:6px;border-radius:50%;background:#b9d9a4}
.sp-hero-metrics{display:flex;gap:28px;flex-wrap:wrap;padding-bottom:2px}.sp-hero-metrics>div{display:flex;flex-direction:column;gap:7px}.sp-hero-metrics strong{font-size:32px;font-weight:400;font-variant-numeric:tabular-nums;letter-spacing:-.04em}.sp-hero-metrics span{font-size:11px;color:#bed8ca}

.sp-workspace-tools{display:flex;align-items:center;gap:16px;margin:22px 0}.sp-workspace-tools h3{font-size:16px}.sp-menu{position:relative;flex:none;font-size:12px}.sp-menu>summary{cursor:pointer;color:var(--sp-muted);padding:10px}.sp-menu>div{position:absolute;right:0;top:100%;display:flex;flex-direction:column;padding:6px;background:var(--sp-paper);border:1px solid var(--sp-line);border-radius:10px;box-shadow:0 8px 30px #0002;min-width:170px;z-index:5}.sp-menu button{padding:12px;text-align:left;border:0;border-radius:6px;background:transparent;color:var(--sp-ink);cursor:pointer;white-space:nowrap}.sp-menu button:hover{background:var(--sp-soft)}
.sp-review-banner{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:16px 20px;margin-top:18px;background:var(--sp-soft);border:1px solid var(--sp-line);border-radius:12px}.sp-review-banner strong{font-size:13px}.sp-review-banner p{font-size:12px;color:var(--sp-muted);margin:5px 0 0;line-height:1.7}.sp-review-banner .ent-actions{flex-wrap:wrap}
.sp-browse-bar{margin-top:22px;display:flex;justify-content:space-between;align-items:center;gap:20px;padding:0 0 16px;border-bottom:1px solid var(--sp-line)}.sp-collections{display:flex;gap:20px;overflow-x:auto;min-width:0}.sp-collections>button{display:flex;align-items:center;gap:7px;appearance:none;border:0;border-bottom:2px solid transparent;padding:10px 0;background:transparent;color:var(--sp-muted);white-space:nowrap;font-size:12px;cursor:pointer}.sp-collections>button[aria-pressed=true]{color:var(--sp-ink);border-bottom-color:var(--sp-accent);font-weight:600}.sp-collections>button>span{background:var(--sp-soft);padding:2px 5px;border-radius:4px;font-size:10px}
.supplier-panel input.sp-search{width:210px;flex:none;border-radius:9px;padding:9px 12px;border-color:var(--sp-line);background:var(--sp-soft);font-size:12px;color:var(--sp-ink)}

.sp-group{margin:26px 0 32px}.sp-overview-groups{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.sp-overview-groups>.sp-group{display:flex;flex-direction:column;min-width:0;margin:22px 0 0}.sp-overview-groups .sp-grid{grid-template-columns:1fr;flex:1}.sp-overview-groups .sp-item{min-height:220px}.sp-section-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;gap:12px}.sp-section-heading h3{display:flex;align-items:center;gap:10px;font-size:14px;font-weight:600;margin:0}.sp-section-heading h3>span{font-size:11px;font-weight:400;color:var(--sp-muted)}.sp-section-heading>button{background:none;border:0;color:var(--sp-muted);font-size:12px;cursor:pointer}
.sp-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.sp-grid-offering,.sp-grid-solution{grid-template-columns:repeat(2,minmax(0,1fr))}.sp-item{display:flex;flex-direction:column;text-align:left;min-width:0;overflow:hidden;padding:0;appearance:none;border:1px solid var(--sp-line);border-radius:15px;background:var(--sp-paper);color:var(--sp-ink);cursor:pointer;transition:box-shadow .18s,transform .18s,border-color .18s}.sp-item:hover{transform:translateY(-3px);box-shadow:0 8px 24px #0000000a;border-color:var(--sp-accent)}.sp-item-image{width:100%;height:150px;object-fit:cover}.sp-item-body{display:flex;flex:1;flex-direction:column;gap:10px;padding:20px 22px}.sp-item-body>strong{font-size:17px;line-height:1.5;letter-spacing:-.02em}.sp-item-description{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;color:var(--sp-muted);font-size:13px;line-height:1.8}.sp-item-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:auto;padding-top:14px;color:var(--sp-muted);font-size:11px}.sp-item-footer>span:last-child{font-size:18px;color:var(--sp-ink)}.sp-tags{display:flex;flex-wrap:wrap;gap:6px}.sp-tags>span{padding:4px 8px;background:var(--sp-soft);color:var(--sp-muted);border-radius:5px;font-size:11px}
.sp-grid-capability .sp-item,.sp-grid-commercial_policy .sp-item{background:var(--sp-soft);border-color:transparent}.sp-grid-case .sp-item{border-top:3px solid var(--sp-line)}
.sp-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:60px 24px;border:1px dashed var(--sp-line);border-radius:16px;margin-top:28px}.sp-empty>span{font-size:44px;color:var(--sp-accent)}.sp-empty h3{font-size:19px}.sp-empty p{max-width:420px;line-height:1.8;color:var(--sp-muted);margin:0 0 24px}
.sp-profile-footer{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:10px;border-top:1px solid var(--sp-line);padding:20px 0;margin-top:28px}.sp-profile-footer>span{margin-right:auto;color:var(--sp-muted);font-size:12px}
.sp-source-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;padding-top:24px}.sp-source{min-width:0;border:1px solid var(--sp-line);border-radius:12px;padding:20px;margin:0 0 12px;overflow-wrap:anywhere}.sp-source h4{font-size:15px;margin:6px 0 12px}.sp-source p{font-size:13px;line-height:1.8}.sp-source a{color:var(--sp-accent);font-size:13px}.sp-source blockquote{margin:15px 0;padding:8px 14px;border-left:2px solid var(--sp-line);background:var(--sp-soft);font-size:13px;line-height:1.8}.sp-source time,.sp-source small{display:block;margin-top:14px;font-size:11px}.sp-muted{color:var(--sp-muted);line-height:1.7}
.ent-dialog.sp-detail{position:fixed;right:16px;top:16px;bottom:16px;width:min(600px,calc(100vw - 32px));max-height:calc(100dvh - 32px);background:var(--sp-paper)}.sp-dialog-scroll{min-height:0;overflow:auto;max-height:calc(100dvh - 80px)}.sp-editor-dialog{background:var(--sp-paper)}.sp-detail-intro>p{font-size:17px;line-height:1.9;margin:12px 0 20px}.sp-detail-section{padding-top:25px;margin-top:24px;border-top:1px solid var(--sp-line)}.sp-detail-section h3{font-size:14px;margin:0 0 18px}.sp-claim{display:grid;grid-template-columns:110px minmax(0,1fr);gap:20px;padding:14px 0;border-bottom:1px solid var(--sp-line)}.sp-claim dt{color:var(--sp-muted);font-size:13px}.sp-claim dd{margin:0;line-height:1.7;overflow-wrap:anywhere}.sp-claim dd p{font-size:13px;margin:7px 0}.sp-status{display:inline-block;font-size:10px;padding:2px 7px;border-radius:4px;background:var(--sp-soft);color:var(--sp-muted);margin-left:10px}.sp-claim small,.sp-claim time{display:block;font-size:11px;color:var(--sp-muted);margin-top:7px}.sp-disclosure{padding:14px;border-radius:8px;background:var(--sp-soft);font-size:13px;line-height:1.8}
.sp-related{display:flex;align-items:center;gap:12px;width:100%;padding:14px 0;text-align:left;border:0;border-bottom:1px solid var(--sp-line);background:none;color:var(--sp-ink);cursor:pointer}.sp-related>span:first-child{font-size:11px;color:var(--sp-muted)}.sp-related strong{flex:1;font-size:13px}.sp-detail-actions{display:flex;gap:10px;flex-wrap:wrap;position:sticky;bottom:0;padding:18px 0 0;background:var(--sp-paper);margin-top:24px;border-top:1px solid var(--sp-line)}
.sp-questions,.sp-editor-questions{padding:13px 16px;background:var(--sp-soft);border-radius:9px;margin:12px 0;font-size:13px}.sp-questions summary,.sp-editor-questions summary{cursor:pointer}
.sp-editor-dialog{max-width:900px}.sp-editor-fields{padding:0;border:0;min-width:0}.sp-editor-layout{display:grid;grid-template-columns:190px minmax(0,1fr);gap:24px;margin-top:22px}.sp-editor-nav{display:flex;flex-direction:column;gap:5px;align-self:start;position:sticky;top:0;max-height:55vh;overflow:auto}.sp-editor-nav>button{appearance:none;text-align:left;padding:11px 12px;background:transparent;border:0;border-radius:8px;color:var(--sp-muted);font-size:12px;cursor:pointer;overflow-wrap:anywhere}.sp-editor-nav>button[aria-pressed=true]{background:var(--sp-soft);color:var(--sp-ink);font-weight:600}.sp-editor-tabs{display:flex;gap:8px;border-bottom:1px solid var(--sp-line);padding-bottom:12px;flex-wrap:wrap}.sp-editor-tabs>button{border:0;border-radius:7px;padding:8px 12px;background:transparent;color:var(--sp-muted);cursor:pointer;font-size:13px}.sp-editor-tabs>button[aria-pressed=true]{background:var(--sp-soft);color:var(--sp-ink)}.sp-editor-dialog .supplier-card{border:0;padding:0;margin:0;min-width:0}.sp-editor-dialog .ent-section{padding:0;margin:0;border:0}.sp-editor-dialog .ent-grid{gap:12px 20px}.sp-editor-dialog .supplier-editor input:not([type=checkbox]),.sp-editor-dialog .supplier-editor select,.sp-editor-dialog textarea{width:100%;padding:10px;border:1px solid var(--sp-line);border-radius:7px;color:var(--sp-ink);background:var(--sp-paper);font:inherit;box-sizing:border-box}.sp-editor-dialog textarea{min-height:90px;resize:vertical}.sp-editor-dialog .supplier-editor details{padding:14px 0;border-top:1px solid var(--sp-line)}.sp-editor-dialog .supplier-editor summary{font-size:13px;font-weight:600;cursor:pointer}.sp-editor-dialog .supplier-editor .ent-field{margin:10px 0}.sp-editor-dialog .supplier-editor fieldset{min-width:0}.sp-editor-dialog .supplier-claim{border-top:1px solid var(--sp-line);padding:12px 0}.sp-editor-dialog .supplier-check{font-size:12px}.sp-editor-dialog .sp-editor-nav>button:last-child{color:var(--sp-accent);margin-top:12px}
.sp-onboarding{max-width:740px;margin:7vh auto;text-align:center;padding:40px 24px}.sp-onboarding-mark{display:grid;place-items:center;width:80px;height:80px;margin:0 auto 28px;border-radius:24px;background:#e8f1eb;color:#295c47;font-size:42px}.ent .sp-onboarding h2{font-size:clamp(25px,3vw,36px);line-height:1.5;letter-spacing:-.03em;margin:14px 0}.sp-onboarding>p:not(.sp-kicker){max-width:480px;margin:0 auto;color:var(--sp-muted);line-height:1.9}.sp-onboarding ol{display:flex;justify-content:center;flex-wrap:wrap;gap:16px 30px;list-style-position:inside;padding:24px 0;margin:16px 0 22px;font-size:13px;color:var(--sp-muted)}@media(min-width:1250px){.ent:has(.supplier-panel) .ent-inner{max-width:1160px}}
@media(max-width:1000px){.sp-hero{grid-template-columns:1fr;padding:28px;gap:24px}.sp-hero-metrics{gap:40px}.sp-hero-metrics strong{font-size:27px}.sp-browse-bar{align-items:stretch;flex-direction:column;gap:12px}.supplier-panel input.sp-search{width:100%}.sp-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.sp-workspace-tools{flex-wrap:wrap}}
@media(max-width:600px){.sp-hero{padding:25px 22px;border-radius:16px}.ent .sp-hero h2{font-size:25px}.sp-hero-status{margin-top:18px}.sp-hero-metrics{justify-content:space-between;gap:12px}.sp-hero-metrics strong{font-size:26px}.sp-workspace-tools{gap:12px}.sp-mode{width:100%;justify-content:space-between}.sp-mode>button{padding:8px;font-size:11px}.sp-workspace-tools>.ent-actions{margin-left:auto}.sp-collections{gap:18px}.sp-grid,.sp-grid-offering,.sp-grid-solution,.sp-source-grid,.sp-overview-groups{grid-template-columns:1fr}.sp-review-banner{align-items:flex-start;flex-direction:column}.sp-editor-layout{grid-template-columns:1fr;gap:18px}.sp-editor-nav{position:static;max-height:150px;border-bottom:1px solid var(--sp-line);padding-bottom:10px}.sp-claim{grid-template-columns:80px minmax(0,1fr);gap:12px}.sp-profile-footer{justify-content:flex-start}.sp-profile-footer>span{width:100%}}
@media(prefers-reduced-motion:reduce){.sp-item{transition:none}.sp-item:hover{transform:none}}
`
