/** Offline preview checks exercise native controls, review state and responsive layouts. */
import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from '../../../apps/web/node_modules/playwright/index.mjs'

test('design components support review, filtering, keyboard dismissal, themes and narrow screens without enterprise requests', { timeout: 60000 }, async t => {
  const runtime = fileURLToPath(new URL('../../../.trade-runtime/', import.meta.url))
  await mkdir(runtime, { recursive: true })
  const evidence = await mkdtemp(join(runtime, 'design-evidence-'))
  const browser = await chromium.launch({ channel: process.platform === 'win32' ? 'msedge' : 'chromium', headless: true })
  t.after(() => browser.close())
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1, reducedMotion: 'reduce' })
  const errors = [], external = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(/^https?:/, route => { external.push(route.request().url()); return route.abort() })
  await page.goto(new URL('../../../.trade-runtime/design-system/index.html', import.meta.url).href)
  await page.getByRole('heading', { name: '让复杂工作，变得从容。' }).waitFor()
  await page.screenshot({ path: join(evidence, 'desktop-light.png'), fullPage: true })
  const filter = page.getByRole('group', { name: '筛选资料状态' })
  await filter.getByRole('button', { name: '待核对', exact: true }).click()
  assert.equal(await page.locator('.td-source-row').count(), 1)
  await filter.getByRole('button', { name: '全部', exact: true }).click()
  await page.getByRole('searchbox', { name: '查找资料' }).fill('missing-source')
  await page.getByRole('heading', { name: '没有找到匹配资料' }).waitFor()
  await page.getByRole('button', { name: '重置筛选' }).click()
  assert.equal(await page.locator('.td-source-row').count(), 3)
  const sourceAction = page.getByRole('button', { name: '查看 产品目录 · 春夏系列.pdf' })
  await sourceAction.click()
  await page.getByRole('dialog', { name: '产品目录 · 春夏系列.pdf' }).waitFor()
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog').count(), 0)
  assert.equal(await sourceAction.evaluate(element => element === document.activeElement), true)
  await page.getByRole('button', { name: '确认内容', exact: true }).click()
  assert.match(await page.locator('#review').innerText(), /已核对/)
  await page.getByRole('button', { name: '重新核对' }).click()
  await page.getByRole('button', { name: '需要补充', exact: true }).click()
  assert.match(await page.locator('#review').innerText(), /待补充/)
  await page.getByRole('button', { name: '重新核对' }).click()
  await page.getByRole('button', { name: '收藏示例' }).click()
  assert.equal(await page.getByRole('button', { name: '已收藏' }).getAttribute('aria-pressed'), 'true')
  const email = page.getByRole('textbox', { name: '联系邮箱' })
  await email.fill('incomplete'); await email.press('Tab')
  assert.equal(await email.getAttribute('aria-invalid'), 'true')
  assert.ok(await email.getAttribute('aria-describedby'))
  await email.fill('name@example.com')
  assert.equal(await email.getAttribute('aria-invalid'), null)
  await page.getByRole('button', { name: '创建示例草稿' }).click()
  await page.getByRole('heading', { name: '你的示例草稿' }).waitFor()
  await page.getByRole('button', { name: '切换深浅主题' }).click()
  assert.equal(await page.locator('.td-root').getAttribute('data-theme'), 'dark')
  await page.screenshot({ path: join(evidence, 'desktop-dark.png'), fullPage: true })
  await page.getByRole('button', { name: 'Switch to English' }).click()
  await page.getByRole('heading', { name: 'Make room for focused work.' }).waitFor()
  assert.equal(await page.locator('html').getAttribute('lang'), 'en')
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.screenshot({ path: join(evidence, 'mobile-dark-en.png'), fullPage: true })
  await page.getByRole('button', { name: '切换为中文' }).click()
  await page.getByRole('button', { name: '切换深浅主题' }).click()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.screenshot({ path: join(evidence, 'mobile-light.png'), fullPage: true })
  assert.equal(await page.locator('.td-spinner').evaluate(element => getComputedStyle(element).animationName), 'none')
  assert.deepEqual(errors, []); assert.deepEqual(external, [])
  t.diagnostic(`Screenshots: ${evidence}`)
})
