/** External credentials are checked by the supplier route on the shipped dsh Web profile. */
import assert from 'node:assert/strict'
import { test } from 'node:test'
import { spawn } from 'node:child_process'
import { chromium } from '../../../apps/web/node_modules/playwright/index.mjs'
import { supplierFixture } from './supplier-fixture.mjs'
import { once } from 'node:events'
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../../../', import.meta.url))

test('supplier workspace edits, confirms, matches, shares and follows up through the real browser', { timeout: 120000 }, async t => {
  const parent = join(root, '.trade-runtime')
  await mkdir(parent, { recursive: true })
  const directory = await mkdtemp(join(parent, 'supplier-api-'))
  let child
  let browser
  t.after(async () => {
    await browser?.close()
    if (child && child.exitCode === null && child.signalCode === null) {
      const exited = once(child, 'exit')
      child.kill()
      await exited
    }
    await rm(directory, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 })
  })
  const token = 'supplier-test-token-000000000000000000000000'
  const patch = join(directory, 'override.yml')
  await writeFile(patch, JSON.stringify([{ id: 'trade-enterprise', config: {
    directory: join(directory, 'data'), externalAgentToken: token, externalSupplierRecords: [], externalDocumentIds: [],
    maxFileBytes: 1048576, maxTotalBytes: 2097152, maxExtractedCharacters: 10000,
    knowledgeChunkCharacters: 512, maxKnowledgeResults: 5, maxDecompressedBytes: 1048576,
    maxArchiveEntries: 100, maxTableCells: 1000,
  } }]))
  child = spawn(process.execPath, [join(root, 'apps/cli/lib/bin.js'), '--profile', 'trade', '--from-default-profile', 'web', '--patch', join(root, 'trade/cordis.patch.yml'), '--patch', patch, '--host', '127.0.0.1', '--port', '0', '--no-open'], {
    cwd: directory, windowsHide: true, env: { ...process.env, DSH_HOME: join(directory, 'home') }, stdio: ['ignore', 'pipe', 'pipe'],
  })
  let logs = ''
  child.stderr.on('data', value => { logs += value })
  const loginUrl = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error(`dsh startup timed out: ${logs}`)), 30000)
    child.once('error', error => { clearTimeout(timer); reject(error) })
    child.once('exit', code => { clearTimeout(timer); reject(new Error(`dsh exited ${code}: ${logs}`)) })
    child.stdout.on('data', value => {
      logs += value
      const match = logs.match(/dsh web: (http:\/\/127\.0\.0\.1:\d+\/\?token=\S+)/)
      if (match) { clearTimeout(timer); resolve(match[1]) }
    })
  })
  const origin = new URL(loginUrl).origin
  browser = await chromium.launch({ channel: process.platform === 'win32' ? 'msedge' : 'chromium', headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' })
  const page = await context.newPage()
  const output = join(root, '.trade-runtime', 'supplier-evidence')
  await mkdir(output, { recursive: true })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(loginUrl)
  await page.addLocatorHandler(page.getByRole('dialog', { name: '内测声明' }), async dialog => { await dialog.getByRole('button', { name: '继续' }).click() })
  await page.addLocatorHandler(page.getByRole('dialog', { name: '添加一个 API Key 开始使用' }), async dialog => { await dialog.getByRole('button', { name: '稍后配置' }).click() })
  const welcome = page.getByRole('dialog', { name: '内测声明' })
  if (await welcome.count()) await welcome.getByRole('button', { name: '继续' }).click()
  const onboarding = page.getByRole('dialog', { name: '添加一个 API Key 开始使用' })
  if (await onboarding.count()) await onboarding.getByRole('button', { name: '稍后配置' }).click()
  await page.getByRole('button', { name: '企业空间', exact: true }).click({ timeout: 20000 })
  await page.getByRole('heading', { name: '先认识你的企业。' }).waitFor()
  assert.equal(await page.locator('.sp-setup input, .sp-setup textarea').count(), 0)
  await page.screenshot({ path: join(output, 'profile-welcome.png') })
  const post = async (path, data) => {
    const response = await context.request.post(`${origin}/api/enterprise${path}`, { data })
    assert.equal(response.status(), 200, await response.text())
    return response.json()
  }
  await post('/profile', { name: '经纬面料', kind: 'enterprise', description: '为服装品牌提供定制印花粘胶面料。', business: '面料设计、打样和批量供应', website: '', contact: '', email: '', phone: '', address: '', logoId: null })
  const catalog = '100% viscose. 130 g/m². Custom printing for apparel brands. Commercial conditions need confirmation.'
  const upload = await context.request.post(`${origin}/api/enterprise/upload`, { headers: { 'x-file-name': 'catalog.txt' }, data: catalog })
  assert.equal(upload.status(), 201)
  const fileId = (await upload.json()).files[0].id
  const graph = supplierFixture(fileId)
  graph.nodes[0].claims = [{ ...graph.nodes[0].claims[0], qualification: '' }, { attribute: 'GSM', value: '130 g/m²', status: 'SELF_DECLARED', qualification: '', validUntil: null, evidenceIds: ['catalog'] }]
  graph.nodes[0].buyerTypes = ['服装品牌']; graph.nodes[0].markets = ['美国']; graph.nodes[0].businessModels = ['OEM']
  for (const [kind, title, summary] of [['offering', '印花粘胶面料', '面向服装品牌的定制面料系列'], ['value_proposition', '小品牌开发支持', '开发范围及数量按工艺确认'], ['case', '夏季连衣裙开发', '客户名称保密，项目结果需凭证核对'], ['partner_program', '海外分销合作', '区域、资格与独家条款待协商'], ['commercial_policy', '打样与交付政策', 'MOQ、交期、付款与物流按询价确认']]) graph.nodes.push({ id: kind, kind, title, summary, productRecordId: null, claims: [] })
  const id = crypto.randomUUID()
  graph.nodes.push({ id: 'featured-case', kind: 'case', title: '秋季面料开发', summary: '从资料中选择的主推项目', productRecordId: null, claims: [] })
  await post('/supplier/draft', { id, expectedRevision: 0, fields: { kind: 'company', name: '经纬面料', description: '为服装品牌提供定制印花粘胶面料。', questions: '', sections: [{ label: '供给', content: 'Custom printed viscose', source: 'Catalog' }], supplier: graph } })
  await page.reload()
  await page.getByRole('button', { name: '企业空间', exact: true }).click({ timeout: 20000 })
  await page.getByRole('tab', { name: '工作台', exact: true }).waitFor()
  assert.equal(await page.getByRole('tab', { name: '工作台', exact: true }).getAttribute('aria-selected'), 'true')
  await page.getByRole('tab', { name: '工作台', exact: true }).press('End')
  assert.equal(await page.getByRole('tab', { name: 'Assistant', exact: true }).evaluate(element => element === document.activeElement), true)
  await page.getByRole('tab', { name: 'Assistant', exact: true }).press('Home')
  await page.locator('.wb-metrics').getByRole('button', { name: /^企业资料/ }).press('Enter')
  assert.equal(await page.getByRole('tab', { name: '企业资料', exact: true }).evaluate(element => element === document.activeElement), true)
  await page.getByRole('tab', { name: '企业档案', exact: true }).click()
  await page.getByRole('button', { name: '编辑档案', exact: true }).click()
  await page.getByRole('textbox', { name: '联系人', exact: true }).fill('未保存的草稿')
  await page.getByRole('tab', { name: '企业档案', exact: true }).click()
  assert.equal(await page.getByRole('textbox', { name: '联系人', exact: true }).inputValue(), '未保存的草稿')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('tab', { name: '企业展示', exact: true }).click()
  await page.locator('.sp-menu > summary').click()
  await page.getByRole('button', { name: '逐项维护', exact: true }).click()
  assert.equal(await page.locator('.supplier-editor textarea:visible').count(), 1)
  await page.locator('.supplier-editor').getByLabel('说明', { exact: true }).first().fill('Custom printed viscose for independent apparel brands.')
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await page.getByRole('button', { name: '审阅并确认', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('我已阅读并确认本次内容').check()
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: '核对来源', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('我已阅读并确认本次内容').check()
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.getByText('已人工核对来源', { exact: false }).waitFor()
  await page.getByRole('button', { name: '证据库', exact: false }).click()
  await page.getByRole('button', { name: '读取原文', exact: true }).click()
  await page.getByRole('dialog').getByText(catalog, { exact: false }).waitFor()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.locator('.sp-collections').getByRole('button', { name: '业务概览', exact: true }).click()
  assert.equal(await page.locator('.supplier-panel textarea').count(), 0)
  assert.equal(await page.locator('.supplier-panel select').count(), 0)
  assert.equal(await page.locator('.sp-profile-aside').count(), 0)
  assert.equal(await page.locator('.sp-hero-metrics').count(), 0)
  await page.getByRole('button', { name: '为企业主视觉选择图片', exact: true }).click()
  await page.getByText('还没有图片。上传后，选择一张用于展示。', { exact: true }).waitFor()
  await page.getByRole('dialog').locator('input[type=file]').setInputFiles(join(root, 'packages/skill/skill-badge/assets/dsh-badge.png'))
  await page.getByRole('dialog').getByRole('button', { name: 'dsh-badge.png', exact: true }).click()
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  await page.locator('.sp-photo-cover img').waitFor()
  await page.getByRole('button', { name: '为产品图片选择图片', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'dsh-badge.png', exact: true }).click()
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  const mediaProfile = (await (await context.request.get(`${origin}/api/enterprise`)).json()).profile
  assert.equal(mediaProfile.media.coverId, mediaProfile.media.nodeImages.offering)
  const invalidMedia = await context.request.post(`${origin}/api/enterprise/profile`, { data: { ...mediaProfile, media: { coverId: fileId, nodeImages: {} } } })
  assert.equal(invalidMedia.status(), 400)
  await page.reload()
  await page.getByRole('button', { name: '企业空间', exact: true }).click()
  await page.getByRole('tab', { name: '企业展示', exact: true }).click()
  await page.locator('.sp-photo-cover img').waitFor()
  await page.locator('.sp-item-offering .sp-photo img').waitFor()
  assert.equal(await page.locator('.sp-item-offering .sp-photo img').count(), 1)
  await page.screenshot({ path: join(output, 'profile-selected-media.png') })
  await page.getByRole('button', { name: '为企业主视觉选择图片', exact: true }).click()
  await page.getByRole('button', { name: '移除展示图片', exact: true }).click()
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  const detached = await (await context.request.get(`${origin}/api/enterprise`)).json()
  assert.equal(detached.profile.media.coverId, null)
  assert.ok(detached.files.some(file => file.id === mediaProfile.media.coverId))
  const deletedMedia = await post('/delete', { id: mediaProfile.media.coverId })
  assert.deepEqual(deletedMedia.profile.media, { coverId: null, nodeImages: {} })
  await page.reload()
  await page.getByRole('button', { name: '企业空间', exact: true }).click()
  await page.getByRole('tab', { name: '企业展示', exact: true }).click()
  await page.getByRole('button', { name: '为企业主视觉选择图片', exact: true }).waitFor()
  assert.equal(await page.locator('.sp-photo img').count(), 0)
  await page.locator('.sp-collections').getByRole('button', { name: '证据库', exact: true }).click()
  await page.getByRole('heading', { name: 'Supplier catalog', exact: true }).waitFor()
  await page.locator('.sp-collections').getByRole('button', { name: '业务概览', exact: true }).click()
  await page.getByLabel('搜索名称、买家或市场').fill('no-such-offering')
  assert.equal(await page.locator('.sp-item').count(), 0)
  await page.getByRole('button', { name: '清空搜索' }).click()
  await page.getByRole('button', { name: '查看 Custom printed viscose', exact: true }).click()
  await page.getByRole('dialog').getByText('130 g/m²', { exact: true }).waitFor()
  await page.keyboard.press('Shift+Tab')
  assert.ok(await page.getByRole('dialog').evaluate(dialog => dialog.contains(document.activeElement)))
  await page.screenshot({ path: join(output, 'profile-detail.png') })
  await page.getByRole('button', { name: '修改此项', exact: true }).click()
  assert.equal(await page.getByLabel('名称', { exact: true }).inputValue(), 'Custom printed viscose')
  await page.getByLabel('说明', { exact: true }).fill('Unsaved edit')
  await page.screenshot({ path: join(output, 'profile-edit.png') })
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('dialog', { name: '放弃未保存的修改？' }).waitFor()
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  assert.equal(await page.getByLabel('说明', { exact: true }).inputValue(), 'Unsaved edit')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  assert.equal(await page.locator('.sp-item').filter({ hasText: 'Unsaved edit' }).count(), 0)
  await page.locator('.ent').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: join(output, 'profile-desktop.png') })
  await page.locator('.sp-menu > summary').click()
  await page.getByRole('button', { name: '采购匹配', exact: true }).click()
  await page.getByLabel('属性', { exact: true }).fill('克重')
  await page.getByLabel('数值要求', { exact: true }).check()
  await page.getByLabel('值（数值包含单位）', { exact: true }).fill('130')
  await page.getByLabel('单位', { exact: true }).fill('gsm')
  await page.getByRole('button', { name: '逐项匹配', exact: true }).click()
  await page.getByText('匹配', { exact: true }).waitFor()
  await page.locator('.supplier-card').filter({ has: page.getByText('匹配', { exact: true }) }).getByRole('button', { name: '发起采购请求' }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('买家姓名').fill('采购测试')
  await dialog.getByLabel('买家邮箱').fill('buyer@example.com')
  await dialog.getByRole('button', { name: '保存请求草稿' }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await page.getByRole('button', { name: '开始跟进', exact: true }).click()
  await page.getByText('跟进中', { exact: true }).waitFor()
  await page.locator('.sp-menu > summary').click()
  await page.getByRole('button', { name: '外部 Agent 接入', exact: true }).click()
  await page.getByLabel(/经纬面料 · 版本/).check()
  await page.getByLabel('catalog.txt', { exact: true }).check()
  await page.getByRole('button', { name: '保存共享范围' }).click()
  await page.getByRole('button', { name: '保存共享范围' }).waitFor({ state: 'visible' })
  await page.waitForFunction(() => !document.querySelector('.supplier-panel button:disabled'))
  const headers = { authorization: `Bearer ${token}` }
  const external = await (await fetch(`${origin}/supplier/v1/query`, { headers })).json()
  assert.equal(external.records[0].id, id)
  const asset = await fetch(`${origin}/supplier/v1/asset?id=${fileId}`, { headers: { ...headers, range: 'bytes=0-9' } })
  assert.equal(asset.status, 206)
  assert.equal(await asset.text(), catalog.slice(0, 10))
  const match = await fetch(`${origin}/supplier/v1/match`, { method: 'POST', headers, body: JSON.stringify({ recordId: id, requirements: [{ attribute: 'GSM', operator: 'equals', value: 130, unit: 'gsm' }] }) })
  assert.equal((await match.json()).candidates[0].status, 'MATCH')
  const inquiry = await fetch(`${origin}/supplier/v1/inquiries`, { method: 'POST', headers, body: JSON.stringify({ id: crypto.randomUUID(), recordId: id, recordRevision: external.records[0].revision, nodeIds: ['printing'], type: 'sample', name: 'API buyer', email: 'api@example.com', message: 'Please confirm sample conditions.' }) })
  assert.equal((await inquiry.json()).status, 'submitted')
  await page.getByLabel('catalog.txt', { exact: true }).uncheck()
  await page.getByRole('button', { name: '保存共享范围' }).click()
  await page.waitForFunction(() => !document.querySelector('.supplier-panel button:disabled'))
  assert.equal((await fetch(`${origin}/supplier/v1/asset?id=${fileId}`, { headers })).status, 404)
  await page.reload()
  await page.getByRole('button', { name: '企业空间', exact: true }).click()
  await page.getByRole('tab', { name: '企业展示', exact: true }).click()
  await page.getByText('已人工核对来源', { exact: false }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForFunction(() => document.querySelector('.ent').getBoundingClientRect().x <= 57)
  await page.locator('.ent').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: join(output, 'profile-mobile.png') })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
  await page.getByRole('button', { name: '查看 Custom printed viscose', exact: true }).click()
  await page.getByRole('dialog').getByText('130 g/m²', { exact: true }).waitFor()
  assert.ok(await page.getByRole('dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth + 1))
  await page.screenshot({ path: join(output, 'profile-detail-mobile.png') })
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog').count(), 0)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.waitForFunction(() => document.body.hasAttribute('data-ds-dark-theme'))
  await page.evaluate(() => Promise.all(document.getAnimations().map(animation => animation.finished.catch(() => undefined))))
  await page.locator('.ent').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: join(output, 'profile-dark.png') })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.locator('.sp-menu > summary').click()
  await page.getByRole('button', { name: '调整展示', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: '服务导向', exact: false }).click()
  assert.deepEqual(await dialog.locator('.sp-plan-preview li strong').allTextContents(), ['解决方案', '生产与服务能力', '合作案例'])
  await dialog.locator('summary').filter({ hasText: '主标题与简介' }).click()
  await dialog.getByLabel('主标题（留空使用企业定位）').fill('为品牌构建面料方案')
  await dialog.getByLabel('简介（留空使用企业介绍）').fill('从开发方案到项目交付。')
  await dialog.locator('summary').filter({ hasText: '首页栏目与顺序' }).click()
  await dialog.getByRole('button', { name: '上移合作案例', exact: true }).click()
  await dialog.getByRole('button', { name: '上移合作案例', exact: true }).click()
  await dialog.locator('summary').filter({ hasText: '主推内容' }).click()
  await dialog.getByLabel('秋季面料开发', { exact: true }).check()
  await page.screenshot({ path: join(output, 'profile-arrange.png') })
  await dialog.getByRole('button', { name: '保存草稿', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.getByRole('heading', { name: '为品牌构建面料方案', exact: true }).waitFor()
  assert.equal(await page.locator('.sp-explorer.sp-focus-services').count(), 1)
  assert.equal(await page.locator('.sp-overview-groups > .sp-group').first().getByRole('heading').textContent(), '合作案例')
  assert.equal(await page.locator('.sp-grid-case .sp-item-open strong').first().textContent(), '秋季面料开发')
  await page.getByRole('button', { name: '查看已确认内容', exact: true }).click()
  assert.equal(await page.locator('.sp-explorer.sp-focus-products').count(), 1)
  await page.getByRole('button', { name: '查看草稿', exact: true }).click()
  const draftState = await (await context.request.get(`${origin}/api/enterprise/supplier`)).json()
  const layoutDraft = draftState.records.find(record => record.status === 'draft')
  assert.equal(layoutDraft.supplier.presentation.headline, '为品牌构建面料方案')
  assert.deepEqual(layoutDraft.supplier.presentation.featuredIds, ['featured-case'])
  assert.equal(draftState.records.find(record => record.id === id).supplier.presentation, undefined)
  await page.getByRole('button', { name: '审阅并确认', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByText('为品牌构建面料方案', { exact: true }).waitFor()
  await dialog.getByLabel('我已阅读并确认本次内容').check()
  await dialog.getByRole('button', { name: '确认', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.reload()
  await page.getByRole('button', { name: '企业空间', exact: true }).click()
  await page.getByRole('tab', { name: '企业展示', exact: true }).click()
  await page.getByRole('heading', { name: '为品牌构建面料方案', exact: true }).waitFor()
  await page.locator('.sp-collections').getByRole('button', { name: '商业政策', exact: true }).click()
  await page.getByRole('button', { name: '查看 打样与交付政策', exact: true }).waitFor()
  await page.locator('.sp-collections').getByRole('button', { name: '业务概览', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForFunction(() => document.querySelector('.ent').getBoundingClientRect().x <= 57)
  await page.locator('.ent').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: join(output, 'profile-service-mobile.png') })
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
  assert.deepEqual(errors, [])
})
